- exonum/src/helpers/fabric/details.rs
Closes: https://github.com/exonum/exonum/issues/251
> Dissalow generate-testnet with 0 nodes.

- exonum/src/helpers/fabric/builder.rs
Closes https://github.com/exonum/exonum/issues/232
I am using `set_hook` here, instead of `catch_unwind` because I need to prevent printing default panic message in `std::*::default_hook`.
The message will look like
```
➜  exonum-configuration git:(cargo-toml) ✗ ./target/debug/examples/configuration 
error: Subcommand not found
```
instead of 
```
➜  exonum-configuration git:(cargo-toml) ✗ ./target/debug/examples/configuration 
thread 'main' panicked at 'Subcommand not found', /Users/vladimirmotylenko/bitfury/exonum/exonum/src/helpers/fabric/clap_backend.rs:84
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Cons: 
1. User can't print backtrace for cmd parsing now. (but he shouldn't want it)
2. We can add color, or other marks, to increase usability
3. It only catch and prints …
> Make panic message cleaner.

- exonum/src/blockchain/config.rs
- exonum/src/blockchain/mod.rs
- exonum/src/helpers/fabric/builder.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/node/state.rs
- exonum/src/node/timeout_adjuster.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/tests/config.rs
- exonum/tests/testdata/config/config01.toml
- exonum/tests/testdata/config/config02.toml
- exonum/tests/testdata/config/config03.toml
- exonum/tests/testdata/config/config04.toml
- exonum/tests/testdata/config/config0_pub.toml
- exonum/tests/testdata/config/config12.toml
- exonum/tests/testdata/config/config13.toml
- exonum/tests/testdata/config/config14.toml
- exonum/tests/testdata/config/config1_pub.toml
- exonum/tests/testdata/config/config23.toml
- exonum/tests/testdata/config/config24.toml
- exonum/tests/testdata/config/config2_pub.toml
- exonum/tests/testdata/config/config34.toml
- exonum/tests/testdata/config/config3_pub.toml
- exonum/tests/testdata/config/template.toml
- sandbox/src/sandbox.rs
Several tasks are handled in this pull request:
1. Additional `Dynamic` timeout adjuster is added.
2. Timeout adjusters should be configured dynamically (#137).
3. Config should be updated only when it is needed (#190).
(#250)
> Timeout adjusters refactoring

- exonum/src/blockchain/mod.rs
- exonum/src/node/consensus.rs
- exonum/src/node/state.rs
Closes https://github.com/exonum/exonum/issues/186
> Fix panic, in handle_block

- exonum/src/blockchain/tests.rs
- exonum/src/encoding/spec.rs
> Fix deserialization panic.

- 3rdparty/leveldb/tests/cache.rs
- 3rdparty/leveldb/tests/comparator.rs
- 3rdparty/leveldb/tests/iterator.rs
- 3rdparty/leveldb/tests/snapshots.rs
> Fix leveldb tests

- .travis.yml
Use parallel build matrix instead of stages, build time: 5:30 min + vm bootstrap 30 sec.
> Make exonum build parallel

- exonum/Cargo.toml
- exonum/src/helpers/mod.rs
- exonum/src/lib.rs
Hey, guys! 🙂 
Finally found some time to test this small change. ⌚️ 
Works for me. ⚙️ 
Closes #194
> Color output into log file

- exonum/src/helpers/mod.rs
> Set fixed width for value of milliseconds in a log entity

- exonum/Cargo.toml
This should fix badge in crates.io
> Fix travis-CI badge

- .travis.yml
- exonum/src/encoding/segments.rs
- exonum/src/encoding/spec.rs
- exonum/src/encoding/tests.rs
- exonum/src/messages/spec.rs
- exonum/src/messages/tests.rs
Closes https://github.com/exonum/exonum/issues/296
After some fuzz tests, and additional review I detected new panics in deserialization.
All test cases are filed in issue.
> Fix malicious buffer deserialization panics.

- .travis.yml
- 3rdparty/profiler/Cargo.toml
- 3rdparty/profiler/src/lib.rs
- exonum/benches/events.rs
- exonum/benches/storage.rs
- exonum/src/events/mod.rs
- exonum/src/events/tests.rs
- exonum/src/helpers/fabric/builder.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/mod.rs
- exonum/src/helpers/types.rs
- exonum/src/lib.rs
- exonum/src/node/timeout_adjuster.rs
- exonum/src/storage/proof_list_index/key.rs
- exonum/src/storage/proof_map_index/key.rs
- sandbox/src/lib.rs
- sandbox/src/sandbox.rs
- sandbox/tests/requests.rs
> Clippy update to 0.0.156

- exonum/Cargo.toml
⚠️ ⚠️ ⚠️ I deleted git path for `exonum_rocksdb` and `exonum_sodiumoxide` dependencies.
> Update Cargo.toml for v0.2

- CHANGELOG.md
- exonum/src/crypto.rs
> Implement `FromStr` for public sodium types.

- CHANGELOG.md
- exonum/src/events/connection.rs
Closes https://github.com/exonum/exonum/issues/332
> Fix panic in network message processing.

- exonum/src/messages/spec.rs
This PR don't let to swallow description of deserialization bugs.
> Add description of deserialization error

- 3rdparty/flamer/Cargo.toml
- 3rdparty/flamer/src/lib.rs
- 3rdparty/profiler/Cargo.toml
- 3rdparty/profiler/src/lib.rs
- exonum/Cargo.toml
For some reasons, `profiler` was broken.
> Fix profiler

- CHANGELOG.md
- exonum/Cargo.toml
- sandbox/Cargo.toml
Bump version to 0.3 and clarify changelog
> Release 0.3

- exonum/src/storage/base_index.rs
Motivation: don't repeat `if`/`else` with panic. :smile:
> Move panic after index name validation into the separate function

- CHANGELOG.md
- exonum/src/storage/db.rs
- exonum/src/storage/mod.rs
Funny thing: in the #371 pull request I actually forgot to add getter for `Patch`. 😅
> Add 'patch' method to the 'Fork' structure

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Without pull request template it's hard to find entry point in reviewing external pull requests. 
Pull request template should help us track changes, and merging pull request faster.
Just read carefully and check the grammar.
> Add pull_request and issue templates.

- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/service.rs
- exonum/src/events/error.rs
- exonum/src/events/tests.rs
- exonum/src/node/mod.rs
- exonum/src/node/state.rs
- exonum/src/storage/db.rs
Fix some typos in comments and messages
- returnts -> returns
- unefficient -> inefficient
- uncommited -> uncommitted
- capacitites -> capacities
- occured -> occurred
- reconect -> reconnect
- rollbakcs -> rollbacks
- [-] Tests for the changes have been added
- [-] Docs have been added / updated
- [-] CHANGELOG.md have been updated
:eyes:
> Fix some typos

- exonum/src/api/private/system.rs
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/node/requests.rs
Fix some typos: "Incomming", "invokations", "shoud", "sended", "addr".
"IncommingConnectionState" is a struct name, but it doesn't seem to be exported anywhere so it doesn't look like a breaking change.
- [-] Tests for the changes have been added
- [-] Docs have been added / updated
- [-] CHANGELOG.md have been updated
:eye: :eye:
> More typos

- .travis.yml
- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/helpers/mod.rs
Just update logger version.
- Not a breaking change
- No need in updating docs
- No need in testing
> Update logger version

- exonum/src/helpers/config.rs
Fixes #428
Long story short:
- Not a breaking change
- No need in updating docs
- No need in testing
> [Fix] Config: Do not swallow error message while toml loading

- exonum/src/events/codec.rs
Regression bug after tokio land.
Execute this bash command:
`echo -e '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | nc 127.0.0.1 6333`
> Fix a bug with codec that cause node to panic.

- CHANGELOG.md
> Fix 0.5.0 release date

- CHANGELOG.md
- exonum/src/helpers/mod.rs
Fix log output
Use `writeln!` in `format_log_record`
> Fix log output (hot fix)

- ARCHITECTURE.md
This PR is ** documentation to improve contributor experience**. It adds an ARCHITECTURE.md file which gives a one-page description of the large moving parts of Exonum. The primary purpose of this code is to allow someone to dive into code.
> ARCHITECTURE.md

- exonum/src/blockchain/transaction.rs
> Beautified code

- exonum/CHANGELOG.md
> Update changelog (transactions macro)

- .travis.yml
No functional changes, just rename travis jobs to better reflect reality.
> Minor: correct job names in .travis.yml

- exonum/CHANGELOG.md
- exonum/src/crypto.rs
> Fix hash implementation for `()`. [ECR-442]

- .gitignore
- .travis.yml
- Cargo.toml
- exonum-dictionary.txt
- exonum/fuzz/.gitignore
- exonum/fuzz/Cargo.toml
- exonum/fuzz/README.md
- exonum/fuzz/fuzz_targets/raw_message.rs
> Add basic fuzz testing suit [ECR-203]

- .circleci/config.yml
This PR adds some basic macOS CI testing.
> circleci: basic macos build [ECR-443]

- .travis.yml
- CONTRIBUTING.md
- README.md
This PR adds deps.rs badge so that users can quickly see how up to date exonum is:
[![dependency status](https://deps.rs/repo/github/exonum/exonum/status.svg)](https://deps.rs/repo/github/exonum/exonum)
Note: I've moved `` comment because it was breaking the line.
> README: Add deps.rs badge [ECR-709]

- README.md
- exonum/README.md
- services/configuration/README.md
- services/time/README.md
- testkit/README.md
What do you think?
[Main readme](https://github.com/vitvakatu/exonum/tree/ecr_593/README.md)
> Rework badges in readmes [ECR-593]

- exonum/src/api/private/system.rs
- exonum/src/api/public/system.rs
See https://github.com/exonum/exonum/pull/446/files#r165302169
> Fix method naming convention in api/{private,public}/system.rs [ECR-660]

- exonum/src/blockchain/service.rs
- exonum/src/node/events.rs
Aaand another _tiny_ PR to fix naming warts.
See https://github.com/exonum/exonum/pull/446/files#r165302899
> Fix method naming convention in blockchain/service.rs [ECR-661]

- testkit/CHANGELOG.md
> Simplify testkit changelog

- .circleci/config.yml
This PR adds simple caching to circleci builds.
> circleci: Add simple cache [ECR-720]

- exonum/src/blockchain/config.rs
> Compare `round_timeout` and `timeout_adjuster.timeout` [ECR-650]

- testkit/CHANGELOG.md
- testkit/src/lib.rs
> Added possibility to init a logger in TestKitBuilder

- exonum/CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/node/mod.rs
- sandbox/src/sandbox.rs
- testkit/src/lib.rs
Before this, PR, `create_genesis_block` was called after each` Node` creation.
> Fix bug with the extra creation of the genesis configuration. [ECR-826]

- exonum/CHANGELOG.md
- exonum/src/storage/base_index.rs
- exonum/src/storage/entry.rs
- exonum/src/storage/indexes_metadata.rs
- exonum/src/storage/key_set_index.rs
- exonum/src/storage/list_index.rs
- exonum/src/storage/map_index.rs
- exonum/src/storage/mod.rs
- exonum/src/storage/proof_list_index/mod.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/src/storage/sparse_list_index.rs
- exonum/src/storage/value_set_index.rs
> Implement runtime index type checks [ECR-705]

- examples/cryptocurrency/examples/demo.rs
- exonum/CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/tests.rs
- exonum/src/blockchain/transaction.rs
- exonum/src/events/network.rs
- exonum/src/node/mod.rs
- exonum/src/storage/db.rs
- exonum/src/storage/memorydb.rs
- exonum/src/storage/rocksdb.rs
- exonum/tests/node.rs
- sandbox/src/sandbox.rs
- testkit/src/checkpoint_db.rs
- testkit/src/lib.rs
- Fix "can't cancel routine" error.
- Add test for shutdown request.
- Add test for a possible regression in "create_genesis_block" behaviour.
> Add shutdown tests [ECR-850], [ECR-847]

- exonum/src/blockchain/transaction.rs
- testkit/tests/counter/counter.rs
- testkit/tests/currency/cryptocurrency.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
This PR fixes usage scenarions of transactions` set in separate modules.
> Make $transaction_set public by default [ECR-845]

- exonum/tests/node.rs
> Disable 'test_node_shutdown_twice' test

- CONTRIBUTING.md
- exonum-dictionary.txt
> Describe pull request and merge strategy

- CHANGELOG.md
- examples/cryptocurrency/examples/demo.rs
- exonum/benches/block.rs
- exonum/benches/storage.rs
- exonum/src/blockchain/tests.rs
- exonum/src/helpers/fabric/builder.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/mod.rs
- exonum/src/node/mod.rs
- exonum/src/storage/list_index.rs
- exonum/src/storage/map_index.rs
- exonum/src/storage/mod.rs
- exonum/src/storage/options.rs
- exonum/src/storage/proof_list_index/tests.rs
- exonum/src/storage/proof_map_index/tests.rs
- exonum/src/storage/rocksdb.rs
- exonum/src/storage/sparse_list_index.rs
- exonum/src/storage/tests.rs
- exonum/tests/testdata/config/config01.toml
- exonum/tests/testdata/config/config02.toml
- exonum/tests/testdata/config/config03.toml
- exonum/tests/testdata/config/config04.toml
- exonum/tests/testdata/config/config12.toml
- exonum/tests/testdata/config/config13.toml
- exonum/tests/testdata/config/config14.toml
- exonum/tests/testdata/config/config23.toml
- exonum/tests/testdata/config/config24.toml
- exonum/tests/testdata/config/config34.toml
- sandbox/examples/merkle_map.rs
Abstract way to adjust settings of RocksDB via node config.
TODO:
> Added DbOptions [ECR-839]

- CHANGELOG.md
> Add the number of PRs

- .travis.yml
> Remove unused environment variables from the Travis script

- examples/cryptocurrency/Cargo.toml
> Set "publish = false" for cryprocurrency example

- exonum/src/blockchain/tests.rs
- exonum/src/encoding/fields.rs
- exonum/src/encoding/segments.rs
- exonum/src/encoding/spec.rs
- exonum/src/encoding/tests.rs
- exonum/src/lib.rs
- exonum/src/messages/raw.rs
- exonum/src/messages/spec.rs
- exonum/src/storage/indexes_metadata.rs
- exonum/src/storage/keys.rs
- exonum/src/storage/proof_map_index/node.rs
- exonum/src/storage/rocksdb.rs
> Add 'deny(unsafe_code)' attribute [ECR-982]

- examples/cryptocurrency/README.md
> Fix repository url in the cryptocurrency example

- CHANGELOG.md
- exonum/src/api/public/blockchain_explorer.rs
- exonum/src/api/public/system.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/src/node/consensus.rs
- exonum/src/node/requests.rs
- sandbox/tests/consensus.rs
> [Discussion] Rename tx/txs to transaction/transactions

- exonum/benches/storage.rs
- exonum/src/crypto.rs
- exonum/src/encoding/mod.rs
- exonum/src/node/timeout_adjuster.rs
- exonum/src/storage/entry.rs
- exonum/src/storage/key_set_index.rs
- exonum/src/storage/list_index.rs
- exonum/src/storage/map_index.rs
- exonum/src/storage/proof_list_index/mod.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/src/storage/sparse_list_index.rs
- exonum/src/storage/value_set_index.rs
Remove workaround for the https://github.com/intellij-rust/intellij-rust/issues/1554 issue.
> Remove `drop` calls in the doc examples

- exonum/src/blockchain/service.rs
Just a tiny correction in the Service example
> Removed the outdated `'static` lifetime in the Service documentation

- CHANGELOG.md
Put the periods, rephrase the last sentence.
> Fix explorer changelog entries (regarding #535)

- CHANGELOG.md
- exonum/src/messages/mod.rs
- exonum/src/messages/protocol.rs
- exonum/src/node/basic.rs
- exonum/src/node/consensus.rs
- exonum/src/node/requests.rs
- exonum/src/sandbox/consensus.rs
> Bunch transactions response [ECR-1029]

- exonum/src/node/consensus.rs
- exonum/src/sandbox/consensus.rs
After https://github.com/exonum/exonum/pull/549 `handle_block` ignore blocks with transactions that already in pool.
> Fix BlockResponse with known transaction bug

- CHANGELOG.md
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- services/time/README.md
- testkit/Cargo.toml
> Release 0.7.0 [ECR-1073]

- CHANGELOG.md
- examples/cryptocurrency-advanced/README.md
- examples/cryptocurrency-advanced/frontend/src/pages/Wallet.vue
- examples/cryptocurrency-advanced/frontend/src/plugins/blockchain.js
- fix wait for acceptance in cryptocurrency advanced demo;
- minor interface improvement.
> Fix interface of cryptocurrency advanced demo

- examples/cryptocurrency-advanced/frontend/index.html
- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/cryptocurrency-advanced/frontend/src/components/Navbar.vue
Frontend navbar broken on tablets and mobile devices.
> Fix navbar collapse

- .appveyor.yml
- README.md
- exonum-dictionary.txt
- exonum/tests/node.rs
Time limit for build is 1 hour in free version, and at the moment it takes almost 50 minutes for `cargo test --all`
> Setup Appveyor [ECR-1090] 

- README.md
> Fix windows build status badge

- exonum/src/node/consensus.rs
Totally missed it during the review, thanks to @vldm.
> Remove useless match in handle_tx function

- exonum/src/node/state.rs
> Add a space to bail message (#650)

- exonum/src/node/consensus.rs
Rename has_full_propose to handle_full_propose.
Rename has_majority_prevotes to handle_majority_prevotes.
Rename has_majority_precommits to handle_majority_precommits.
> Rename has_* methods in consensus.rs, update sandbox and comments (#637)

- CHANGELOG.md
- exonum/src/helpers/metrics.rs
> Update changelog with #620 pull request changes

- exonum/src/sandbox/consensus.rs
This is the second part from previous commit.
> Also update method names in comments in sandbox/consensus.rs (#637)

- .travis.yml
> Set fixed cspell version

- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/timestamping/README.md
- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
- examples/timestamping/frontend/src/pages/Transaction.vue
- examples/timestamping/frontend/src/plugins/blockchain.js
- testkit/examples/server/package-lock.json
- testkit/examples/server/package.json
Update light client to fix potential security vulnerabilities caused by third-party dependencies.
> update light client

- exonum/src/encoding/error.rs
> Fixed doc typo

- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/crypto.rs
- exonum/src/encoding/fields.rs
- exonum/src/encoding/serialize/json.rs
- exonum/src/encoding/tests.rs
- exonum/src/lib.rs
- exonum/src/storage/keys.rs
- exonum/src/storage/values.rs
The Decimal datatype is crucial for financial applications hence we have to support it.
> Support Decimals

- CHANGELOG.md
- exonum/src/encoding/serialize/mod.rs
- exonum/src/storage/proof_list_index/tests.rs
- exonum/src/storage/proof_map_index/proof.rs
- exonum/src/storage/proof_map_index/tests.rs
Currently deserialize for MapProofs are broken.
> Fix deserialize for proofs [ECR-1388]

- exonum/tests/node.rs
Since it was decided that this test has wrong idea in its basis, I removed it.
> Removed test_node_shutdown_twice [ECR-1161]

- exonum-dictionary.txt
- services/configuration/Cargo.toml
- services/configuration/src/api.rs
- services/configuration/src/lib.rs
- services/configuration/src/schema.rs
- services/configuration/src/tests/api.rs
- services/configuration/src/tests/mod.rs
- services/configuration/src/transactions.rs
MaybeVote is converted to generic struct. The rest of implementation is straight forward.
closes #634
> Add VoteAgainst to configuration service

- exonum/src/blockchain/config.rs
- exonum/src/sandbox/consensus.rs
We are using a newer format where https://github.com/rust-lang-nursery/rustfmt/issues/1777 issue is fixed.
> Remove rustfmt_skip attribute

- README.md
Add link to example of timestamping service application
> Add link to timestamping service

- exonum/src/crypto.rs
> Add doc-examples for SignStream [ECR-1265]

- exonum/src/blockchain/transaction.rs
- exonum/src/encoding/fields.rs
- exonum/src/encoding/segments.rs
- exonum/src/encoding/serialize/mod.rs
- exonum/src/encoding/spec.rs
- exonum/src/helpers/fabric/context_key.rs
Small changes to the descriptions of macros at https://docs.rs/exonum/0.7.0/exonum/
> Improvements to  macros descriptions ar docs.rs

- exonum/tests/balance_service.rs
> Ignore test_duplicated_transaction

- exonum/src/node/consensus.rs
No swearing, for the heck's sake!
> Removed bad comment in node/consensus.rs

- .gitignore
- .travis.yml
- cspell.sh
- package-lock.json
- package.json
Removed some redundant gitignore entries
> Cleanup .gitignore entries

- testkit/tests/system_api.rs
Post-fixes proposed by @slowli
> Service metainfo endpoint [ECR-792]

- CHANGELOG.md
- exonum/src/blockchain/service.rs
> Fix incorrect peer status for turned off node [ECR-1370]

- exonum/src/storage/keys.rs
Added macro for crypto types
Updated Hash and PublicKey to implement StorageKey via macro
> Added StorageKey implementation for Signature

- exonum/src/api/public/system.rs
- exonum/src/blockchain/service.rs
- testkit/tests/system_api.rs
> Add API endpoint to check consensus status [ECR-1649]

- exonum/src/api/private/system.rs
- exonum/src/blockchain/service.rs
Now POST request `consensus_enabled` return BadRequest response.
> POST request to "consensus_enabled" endpoint to auditor returns incorrect response [ECR-1756]

- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
> update exonum-client to latest

- exonum/src/node/basic.rs
> Removed unnecessary variable

- .travis.yml
- exonum/src/encoding/segments.rs
- exonum/src/helpers/fabric/internal.rs
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/node/state.rs
- exonum/src/storage/proof_list_index/proof.rs
> Fix rustfmt CI script, apply fmt.

- exonum/src/crypto/mod.rs
- exonum/src/events/noise/mod.rs
- exonum/src/events/noise/tests.rs
- exonum/src/events/noise/wrappers/sodium_wrapper/handshake.rs
- exonum/src/events/noise/wrappers/sodium_wrapper/wrapper.rs
- exonum/src/events/tests.rs
- exonum/src/helpers/fabric/context_key.rs
- exonum/src/node/state.rs
- exonum/src/sandbox/sandbox.rs
> Remove allow(expl_impl_clone_on_copy)

- examples/cryptocurrency-advanced/README.md
> fix link to frontend tutorial

- CHANGELOG.md
> proofread changelog for 0.9 release

- exonum/src/node/events.rs
> fix consensus enable message handler

- exonum/benches/criterion/lib.rs
- exonum/benches/criterion/transactions.rs
> Transactions benchmark

- .travis.yml
> Remove cargo-audit completely

- exonum/tests/config.rs
> Fix resolve ip address from localhost on windows os

- exonum/src/sandbox/consensus/basic.rs
- exonum/src/sandbox/consensus/transactions.rs
- exonum/src/sandbox/consensus/unsynchronized_message.rs
- exonum/src/sandbox/sandbox_tests_helper.rs
- exonum/src/sandbox/timestamping.rs
removal of the useless comment
using constant in the sandbox
>  [ECR-1627] TODO cleanup pt.1

- exonum/src/api/node/public/system.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/sandbox/consensus/transactions.rs
- exonum/src/sandbox/sandbox.rs
- exonum/src/storage/tests.rs
This pull request should fix overflow during persistent pool manipulation.
TODO:
> Fix pool overflow

- CHANGELOG.md
> Update changelog with 0.9.1 release

- examples/cryptocurrency-advanced/frontend/.babelrc
- examples/cryptocurrency-advanced/frontend/.gitignore
- examples/cryptocurrency-advanced/frontend/package.json
- examples/timestamping/frontend/.babelrc
- examples/timestamping/frontend/.gitignore
- examples/timestamping/frontend/package.json
Downgrade babel to stable version.
> Fix npm warnings in demos

- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/timestamping/frontend/package-lock.json
- testkit/server/package-lock.json
- testkit/server/package.json
To fix known security vulnerabilities in 3rd party npm dependencies.
> Update npm lock files

- testkit/server/package-lock.json
> update testkit npm dependencies

- examples/cryptocurrency-advanced/frontend/package.json
- examples/cryptocurrency-advanced/frontend/src/pages/Wallet.vue
- examples/cryptocurrency-advanced/frontend/src/plugins/blockchain.js
- examples/cryptocurrency-advanced/frontend/tests/blockchain.test.js
- examples/timestamping/frontend/package.json
- examples/timestamping/frontend/src/plugins/blockchain.js
- examples/timestamping/frontend/tests/blockchain.test.js
> refactor js business logic in demos; update tests

- exonum/src/storage/list_index.rs
- exonum/src/storage/map_index.rs
- exonum/src/storage/proof_list_index/tests.rs
- exonum/src/storage/proof_map_index/tests.rs
- exonum/src/storage/sparse_list_index.rs
This PR aims to improve simple unit testing of collections.
> Test removing elements from indexes [ECR-2132]

- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
> Update npm dependencies in demos

- .gitignore
- exonum/src/api/mod.rs
- exonum/src/api/node/public/explorer.rs
- exonum/src/api/websocket.rs
- exonum/src/node/consensus.rs
There are no tests yet :( We should work on test infrastructure to test websockets.
> Fix websockets [ECR-2242]

- .travis.yml
- crypto/src/lib.rs
- exonum/src/blockchain/transaction.rs
- exonum/src/explorer/mod.rs
- exonum/src/messages/raw.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/src/storage/value_set_index.rs
This should fix Travis builds which are occasionally failing since #876 has been merged.
We fix the broken documentation links, make sure the problem will be noticed when we face it again, and do some cleanup of old workarounds. See commit messages for details.
> Fix and improve documentation checks

- exonum/src/blockchain/mod.rs
> Change error msg when transaction execution fails. [ECR-1267]

- exonum/src/events/network.rs
> Fix max incoming connections limit check

- CHANGELOG.md
- exonum/src/api/node/private/mod.rs
- exonum/src/blockchain/service.rs
- exonum/src/events/network.rs
- exonum/src/events/tests.rs
- exonum/src/node/basic.rs
- exonum/src/node/mod.rs
- exonum/src/node/state.rs
Fix some bugs caused by the transition towards one connection between peers.
> Fix /healthcheck and /peers endpoints [ECR-2396]

- testkit/Cargo.toml
- testkit/examples/timestamping.rs
- testkit/src/api.rs
- testkit/src/lib.rs
- testkit/src/network.rs
- testkit/src/server.rs
- testkit/tests/counter/counter.rs
- testkit/tests/counter/main.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
- testkit/tests/inflating_currency/main.rs
- testkit/tests/service_hooks/hooks.rs
- testkit/tests/service_hooks/main.rs
But can be reviewed separately
> Message refactor for testkit

- README.md
- exonum-dictionary.txt
#937 is merged, so we can add the badge.
> Add codecov badge

- examples/timestamping/backend/Cargo.toml
- examples/timestamping/backend/src/api.rs
- examples/timestamping/backend/src/main.rs
- examples/timestamping/backend/src/transactions.rs
- examples/timestamping/backend/tests/api.rs
> Refactor Timestamping service to new message

- services/time/examples/simple_service.rs
- services/time/src/lib.rs
- services/time/src/transactions.rs
- services/time/tests/test_exonum_time.rs
> Refactor time service to new messages module

- exonum/src/events/network.rs
> Add new check for outgoing connections [ECR-2434]

- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency-advanced/backend/src/main.rs
- examples/timestamping/backend/Cargo.toml
- examples/timestamping/backend/src/main.rs
- services/configuration/src/api.rs
- services/configuration/src/cmd.rs
- services/configuration/src/lib.rs
- services/configuration/src/schema.rs
- services/configuration/src/tests/api.rs
- services/configuration/src/tests/mod.rs
- services/configuration/src/transactions.rs
> Refactor configuration service to new messages.

- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/cryptocurrency-advanced/frontend/src/plugins/blockchain.js
- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
- examples/timestamping/frontend/src/plugins/blockchain.js
> update light client; simplify proof checks in demos

- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
Fixed a bug with processing malicious transaction.
> Fix invalid transaction process.

- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
> remove outdated dependency added by chance

- examples/cryptocurrency-advanced/frontend/src/pages/Block.vue
- examples/cryptocurrency-advanced/frontend/src/pages/Transaction.vue
- examples/timestamping/frontend/src/pages/Transaction.vue
According changes in explorer API.
> Fix broken transaction page

- exonum/src/events/network.rs
When some node A initialize connect to other node B, node A call method `peer_addr` which could return error, if other node was shutdown between connection initialization and this method calling. (Os return error 22, `invalid argument`)
> Fixed a bug with panic on shutdown other node. [ECR-2476]

- exonum/Cargo.toml
> Added a temporary dependency ring for being compatible with rust 1.27.2

- exonum/src/blockchain/transaction.rs
> Fix documentation for TransactionResult

- .github/CODEOWNERS
Some changes in CODEOWNERS structure due to changes in the team.
> Some changes in CODEOWNERS

- .github/PULL_REQUEST_TEMPLATE.md
- exonum-dictionary.txt
I think the following template (mostly taken from EJB repository) will slightly improve our reviews. By checking each box contributor explicitly announces, that their PR is ready for merge.
What do you think?
> Improve PR tempate

- CHANGELOG.md
- examples/cryptocurrency/Cargo.toml
- examples/cryptocurrency/build.rs
- examples/cryptocurrency/src/lib.rs
- examples/cryptocurrency/src/proto/cryptocurrency.proto
- examples/cryptocurrency/src/proto/mod.rs
- examples/cryptocurrency/tests/api.rs
- examples/cryptocurrency/tests/tx_logic.rs
- examples/timestamping/backend/Cargo.toml
- examples/timestamping/backend/build.rs
- examples/timestamping/backend/src/lib.rs
- examples/timestamping/backend/src/proto/mod.rs
- examples/timestamping/backend/src/proto/timestamping.proto
- examples/timestamping/backend/src/schema.rs
- examples/timestamping/backend/src/transactions.rs
- examples/timestamping/backend/tests/api.rs
> Other services to protobuf

- exonum/src/node/basic.rs
Some improvement in log output
> Tiny log improvement

- CHANGELOG.md
- examples/cryptocurrency-advanced/backend/src/api.rs
- examples/cryptocurrency/src/lib.rs
- exonum-dictionary.txt
- exonum/src/proto/mod.rs
- exonum/src/proto/schema/exonum/tests.proto
- exonum/src/proto/tests.rs
1) Implement `ProtobufConvert` for protobuf maps.
2) Add breaking changes to CHANGELOG.
---
> Add protobuf convert for maps + fix CHANGELOG [ECR-2733]

- .travis.yml
- package-lock.json
- testkit/server/package-lock.json
- testkit/server/package.json
- testkit/server/test/index.js
- testkit/server/test/protocol.js
- testkit/server/test/service.js
Fix tests in testkit/src/server
> Fix testkit tests

- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/derive/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- testkit/Cargo.toml
- testkit/server/Cargo.toml
A final commit before release 0.10
> Release 0.10

- README.md
- exonum/README.md
- services/configuration/README.md
- services/time/README.md
- testkit/README.md
Update REAMDE files of crates.
> Fix README of exonum-time crate.

- CHANGELOG.md
- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/derive/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
Added info about patch releases.
> CHANGELOG actualization

- CHANGELOG.md
- components/crypto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- exonum/src/helpers/fabric/builder.rs
- exonum/src/lib.rs
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- testkit/Cargo.toml
- testkit/server/Cargo.toml
> Release 0.10.1

- CHANGELOG.md
- components/crypto/src/lib.rs
- exonum/src/storage/keys.rs
- exonum/src/storage/values.rs
https://github.com/exonum/exonum/issues/685
---
> Support i/u128 for CryptoHash, StorageKey, StorageValue

- CHANGELOG.md
- components/crypto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- testkit/Cargo.toml
- testkit/server/Cargo.toml
> Release 0.10.2

- CHANGELOG.md
- exonum/src/helpers/fabric/details.rs
> Added allow origins in dev mode

- .travis.yml
- CHANGELOG.md
- components/crypto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- testkit/Cargo.toml
In practice, too many problems with pined versions.
> Unpin versions of dependencies

- services/configuration/README.md
Links to documentation must be updated due to latest changes on exonum.com/doc
---
> Update link to the documentation

- examples/cryptocurrency-advanced/README.md
- examples/cryptocurrency-advanced/docker/Dockerfile
- examples/timestamping/README.md
- examples/timestamping/docker/Dockerfile
- examples/timestamping/docker/launch.sh
- exonum-dictionary.txt
Cryptocurrency-advanced docker image was updated.
Timestamping docker image was added.
> Update docker images

- CHANGELOG.md
- exonum/src/proto/mod.rs
- exonum/src/proto/schema/exonum/helpers.proto
- exonum/src/proto/tests.rs
> Add ProtobufConvert for Signature

- .travis.yml
- exonum/src/events/network.rs
- exonum/src/storage/db.rs
- exonum/src/storage/proof_list_index/proof.rs
Update rust version in Travis CI script to fix build 
> Update rust version in Travis CI

- .travis.yml
- CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/events/network.rs
- exonum/src/proto/mod.rs
- exonum/src/proto/schema/exonum/helpers.proto
- exonum/src/proto/tests.rs
- exonum/src/storage/db.rs
- exonum/src/storage/proof_list_index/proof.rs
This PR introduces a new entity: `StaticServiceDispatcher` which is responsible for work with statically created services. It encapsulates work with services and transaction execution.
---
See: https://jira.bf.local/browse/ECR-2845
> Old behavior dispatcher

- exonum/src/lib.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust.rs
WIP
See tests of runtime/rust.rs to get an idea about dataflow into runtime environment.
---
> Add basic runtime env interface + rust implementation

- CHANGELOG.md
- exonum/src/api/node/public/system.rs
- testkit/tests/system_api.rs
---
See: https://jira.bf.local/browse/ECR-2925
> Changed a response for healthcheck end-point [ECR-2925]

- exonum/src/runtime/dispatcher.rs
- exonum/src/runtime/error.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust.rs
Dispatcher entity implementation.
> Basic dispatcher functionality

- exonum/Cargo.toml
- exonum/src/proto/mod.rs
- exonum/src/proto/schema/exonum/runtime.proto
- exonum/src/proto/schema/exonum/tests.proto
- exonum/src/proto/tests.rs
- exonum/src/runtime/dispatcher.rs
- exonum/src/runtime/error.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/service.rs
- exonum/src/runtime/rust/tests.rs
* rust artifact with semver, protobuf for common types
* initialization to rust runtime and services
* unwraps are changed to proper error handling + added common error consts
> Rust artifact and additional functionality for rust runtime.

- .travis.yml
- components/crypto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs
- exonum/src/lib.rs
- exonum/tests/collections/list.rs
- exonum/tests/collections/main.rs
- exonum/tests/collections/map.rs
- exonum/tests/collections/set.rs
- exonum/tests/proof_map_index.rs
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- testkit/Cargo.toml
- testkit/server/package.json
Update some dependencies and light refactoring. Prepare to 0.11 release
> Updated some dependencies

- CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/transaction.rs
Tiny internal improvements to support services with dynamic names.
> Add service_name to TransactionContext

- CHANGELOG.md
- exonum/src/api/node/public/explorer.rs
- testkit/tests/counter/main.rs
> Fix `BlockInfo` serialization

- exonum/benches/criterion/block.rs
- exonum/benches/criterion/transactions.rs
- exonum/src/events/codec.rs
- exonum/src/explorer/mod.rs
- exonum/src/messages/authorization.rs
- exonum/src/messages/protocol.rs
- exonum/src/messages/tests.rs
- exonum/src/node/requests.rs
- exonum/src/sandbox/consensus/transactions.rs
- testkit/tests/service_hooks/hooks.rs
> Fixup pb messages

- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/lib.rs
- exonum/src/storage/rocksdb.rs
Preparing to move to merkledb.
> Use rocksdb crate instead of exonum_rocksdb.

- testkit/src/lib.rs
Currently, it's possible to break a testkit server by concurrently sending transactions and creating blocks. The problem seems to be specific to the testkit server (i.e., does not affect real Exonum nodes), since in real nodes all merges are performed on a single thread.
I didn't have time to write targeted tests for this bug, but the scenario to reproduce is described above.
> Fix concurrent patch merge in testkit server

- exonum/src/api/mod.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/transaction.rs
- exonum/src/node/consensus.rs
- exonum/src/proto/mod.rs
- exonum/src/proto/schema/exonum/configuration.proto
- exonum/src/runtime/configuration_new/errors.rs
- exonum/src/runtime/configuration_new/mod.rs
- exonum/src/runtime/configuration_new/schema.rs
- exonum/src/runtime/configuration_new/transactions.rs
- exonum/src/runtime/dispatcher.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/service.rs
- exonum/src/runtime/rust/tests.rs
This PR will contain functionality to deploy services at the node start through config file with deploy/init transactions.
---
See: https://jira.bf.local/browse/ECR-2917
> Dynamic services integration

- components/derive/Cargo.toml
- components/derive/src/lib.rs
- components/derive/src/pb_convert.rs
- components/derive/src/service_interface.rs
- components/derive/src/tx_set.rs
- exonum/src/lib.rs
- exonum/src/runtime/configuration_new/mod.rs
- exonum/src/runtime/rust/service.rs
- exonum/src/runtime/rust/tests.rs
> Remove macro from service interface trait definition

- exonum/src/blockchain/mod.rs
- exonum/src/runtime/configuration_new/mod.rs
- exonum/src/runtime/dispatcher.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/service.rs
- exonum/src/runtime/rust/tests.rs
> Add support of state hash calculation into runtimes & services

- LICENSE
- components/derive/Cargo.toml
- components/merkledb/Cargo.toml
- components/merkledb/LICENSE
- components/merkledb/README.md
- components/merkledb/examples/blockchain.rs
- components/merkledb/src/lib.rs
- examples/cryptocurrency-advanced/LICENSE
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/cryptocurrency/LICENSE
- examples/timestamping/LICENSE
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
- services/configuration/LICENSE
- services/time/Cargo.toml
- services/time/LICENSE
- testkit/Cargo.toml
- testkit/LICENSE
Added readme.md to merkledb crate.
---
> Add readme to merkledb.

- services/configuration/doc/testnet-api-tutorial.md
> Optimize testnet tutorial

- components/merkledb/src/proof_list_index/tests.rs
> Fix merkledb compilation as independent module

- CHANGELOG.md
- components/merkledb/src/key_set_index.rs
- components/merkledb/src/proof_list_index/tests.rs
- components/merkledb/src/value_set_index.rs
> Add length to ValueSetIndex and KeySetIndex

- components/derive/src/tx_set.rs
- exonum/src/blockchain/mod.rs
- exonum/src/messages/protocol.rs
- exonum/src/proto/schema/exonum/protocol.proto
- exonum/src/proto/schema/exonum/runtime.proto
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/tests.rs
> Rename dispatch to call_info

- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
- testkit/server/package-lock.json
- testkit/server/package.json
> Update js dependencies

- .travis.yml
- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/cryptocurrency-advanced/frontend/package.json
- examples/timestamping/frontend/package-lock.json
- examples/timestamping/frontend/package.json
- package-lock.json
- package.json
- testkit/server/package-lock.json
- testkit/server/package.json
> Update js dependencies part 2

- .travis.yml
- components/merkledb/src/sparse_list_index.rs
- examples/cryptocurrency/tests/api.rs
- examples/cryptocurrency/tests/tx_logic.rs
- exonum-dictionary.txt
- exonum/src/api/mod.rs
- exonum/src/api/node/public/system.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/service.rs
- exonum/src/messages/authorization.rs
- exonum/src/messages/mod.rs
- exonum/src/messages/protocol.rs
- exonum/src/runtime/dispatcher.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/tests.rs
- testkit/src/lib.rs
> Some refactoring by clippy suggestion

- .travis.yml
> Changes in travis cache

- ARCHITECTURE.md
Actualizing the architecture description.
> Update ARCHITECTURE.md file

- CHANGELOG.md
- components/merkledb/src/db.rs
- components/merkledb/src/views/tests.rs
- exonum/benches/criterion/block.rs
- exonum/src/blockchain/mod.rs
- exonum/src/node/consensus.rs
- exonum/src/node/state.rs
- exonum/tests/explorer/blockchain/mod.rs
- testkit/src/checkpoint_db.rs
- testkit/src/lib.rs
Implement `From<Patch>` trait for `Fork`. 
---
> Create fork from patch.

- exonum/src/helpers/fabric/details.rs
> Fix origin

- components/derive/Cargo.toml
- components/derive/src/lib.rs
- components/derive/src/pb_convert.rs
- components/derive/src/tx_set.rs
> Update dependencies of derive crate

- CHANGELOG.md
- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/derive/Cargo.toml
- components/merkledb/Cargo.toml
- components/merkledb/README.md
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- package.json
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- services/time/README.md
- testkit/Cargo.toml
- testkit/README.md
- testkit/server/Cargo.toml
> Release 0.12

- exonum/src/helpers/fabric/maintenance.rs
> Clear cache fix

- testkit/server/package-lock.json
> Update js dependency

- CHANGELOG.md
- exonum-dictionary.txt
- exonum/src/api/node/private/mod.rs
- exonum/src/node/events.rs
- exonum/src/node/mod.rs
- exonum/src/runtime/api.rs
- exonum/src/sandbox/consensus/transactions.rs
- exonum/src/sandbox/mod.rs
- testkit/src/lib.rs
- testkit/tests/system_api.rs
The functionality is redundantly now due to #1404
---
See: https://jira.bf.local/browse/ECR-3466
> Remove rebroadcast transactions functionality [ECR-3466]

- CHANGELOG.md
- components/merkledb/src/backends/rocksdb.rs
- components/merkledb/src/options.rs
- examples/timestamping/backend/src/proto/service.proto
- exonum-dictionary.txt
- exonum/src/explorer/mod.rs
- exonum/tests/testdata/config/more_validators/cfg/0/node.toml
- exonum/tests/testdata/config/more_validators/cfg/1/node.toml
- exonum/tests/testdata/config/more_validators/cfg/2/node.toml
- exonum/tests/testdata/config/more_validators/cfg/3/node.toml
- exonum/tests/testdata/config/with_pass/cfg/0/node.toml
- exonum/tests/testdata/config/without_pass/cfg/0/node.toml
- exonum/tests/testdata/config/without_pass/cfg/1/node.toml
- exonum/tests/testdata/config/without_pass/cfg/2/node.toml
- exonum/tests/testdata/config/without_pass/cfg/3/node.toml
---
See: https://jira.bf.local/browse/ECR-3440
> Add a possibility to specify compression algorithm for the database [ECR-3440]

- components/merkledb/benches/storage.rs
- components/merkledb/src/lib.rs
- components/merkledb/src/proof_list_index/key.rs
- components/merkledb/src/proof_list_index/mod.rs
- components/merkledb/src/proof_list_index/proof.rs
- components/merkledb/src/proof_list_index/tests.rs
- components/merkledb/src/proof_map_index/mod.rs
- components/merkledb/src/proof_map_index/proof.rs
- exonum/benches/criterion/crypto.rs
- exonum/benches/criterion/transactions.rs
- exonum/src/events/noise/tests.rs
- exonum/src/explorer/mod.rs
- testkit/tests/counter/main.rs
This PR introduces flat (non-recursive) structure of `ListProof`s.
> Flat list proofs

- cli/src/lib.rs
Just accidentally spotted a TODO in EJB configuration implementation. This change makes dependency control much easier.
---
> Reexport structopt crate from CLI crate

- CHANGELOG.md
- components/merkledb/src/backends/rocksdb.rs
- components/merkledb/src/db.rs
- components/merkledb/src/tests.rs
~~This PR:~~
* ~~exposes [RocksDb checkpoints][1] via the `Database` trait method;~~
* ~~reimplements internal `CheckpointDb` structure of the `exonum-testkit` crate using this new API.~~
New version of this PR switches paradigm a bit:
* [RocksDb checkpoints][1] functionality now exposed via `RocksDB::create_checkpoint` method.
* `dyn Database` trait object can now be downcasted to a concrete implementation.
---
See: https://wiki.bf.local/pages/viewpage.action?pageId=31306417
[1]: https://github.com/facebook/rocksdb/wiki/Checkpoints
> Database create checkpoint

- exonum/src/blockchain/mod.rs
- exonum/src/node/events.rs
- exonum/src/runtime/dispatcher/mod.rs
- exonum/src/runtime/dispatcher/tests.rs
- exonum/src/runtime/mod.rs
With such a method runtimes other that `Rust` will be able to be stopped gracefully.
> Add shutdown method into runtime trait

- CODE_OF_CONDUCT.md
- README.md
> Update contact email address

- cli/src/lib.rs
It turned out that I have broken supervisor creation in the #1473
Shame on me: I knew about it, but forgot to add a fix.
Indirectly it means that we are very good at nitpicking our pull requests, but nevertheless can approve a PR with some big issues not fixed yet `¯\_(ツ)_/¯`
> Fix supervisor creation

- exonum/src/api/node/public/explorer.rs
This change may improve liveness on highload.
> Avoid waiting in the `add_transaction` endpoint [ECR-3222]

- exonum/src/helpers/mod.rs
- exonum/src/helpers/multisig.rs
- exonum/src/node/state.rs
- services/supervisor/Cargo.toml
- services/supervisor/src/errors.rs
- services/supervisor/src/lib.rs
- services/supervisor/src/proto/schema.proto
- services/supervisor/src/proto/service.proto
- services/supervisor/src/proto_structures.rs
- services/supervisor/src/schema.rs
- services/supervisor/src/transactions.rs
- services/supervisor/tests/supervisor/config.rs
- services/supervisor/tests/supervisor/consensus_config.rs
- services/supervisor/tests/supervisor/inc.rs
- services/supervisor/tests/supervisor/main.rs
- services/supervisor/tests/supervisor/utils.rs
- testkit/src/lib.rs
- testkit/src/simple_supervisor/mod.rs
- testkit/src/simple_supervisor/tests.rs
propose_config_change and confirm_config_change transaction implemented
---
See: https://jira.bf.local/browse/ECR-3583
> Implement configuration update logic in Supervisor [ECR-3583]

- services/supervisor/src/api.rs
- services/supervisor/src/lib.rs
- services/supervisor/tests/supervisor/config.rs
- services/supervisor/tests/supervisor/config_api.rs
- services/supervisor/tests/supervisor/main.rs
---
See: https://jira.bf.local/browse/ECR-3610
> Implement API endpoints that shows config proposals in Supervisor [ECR-3610]

- CHANGELOG.md
- exonum/src/api/node/public/explorer.rs
- testkit/tests/counter/main.rs
See: https://jira.bf.local/browse/ECR-3600
> Include actual blockchain height in block response [ECR-3600]

- .travis.yml
> Try to fix an issue with cache in TravisCI

- .travis.yml
> Remove cargo cache from travis

- testkit/src/builder.rs
- testkit/src/lib.rs
See: https://jira.bf.local/browse/ECR-3275
> Fix some of the testkit ignored doctests

- exonum/src/helpers/mod.rs
- exonum/src/helpers/validator.rs
- exonum/src/runtime/rust/service.rs
- services/supervisor/src/lib.rs
- services/time/src/lib.rs
> Remove validator_id method from AfterCommitContext

- cli/src/command/finalize.rs
- cli/src/command/generate_config.rs
- cli/src/command/generate_template.rs
- cli/src/command/maintenance.rs
- cli/src/command/mod.rs
- cli/src/command/run.rs
- cli/src/command/run_dev.rs
- cli/src/config.rs
- cli/src/password.rs
A big question: how the hell CI was green? O_o
> Fix serde imports in exonum-cli

- exonum/src/messages/types.rs
- exonum/src/proto/schema/exonum/consensus.proto
---
See: https://jira.bf.local/browse/ECR-3478
> Clarify SignedMessage documentation [ECR-3478]

- services/supervisor/src/proto/service.proto
- services/supervisor/src/proto_structures.rs
- services/supervisor/src/transactions.rs
> Remove data duplication from DeployConfirmation [ECR-3770]

- exonum/src/runtime/mod.rs
- services/supervisor/src/lib.rs
- services/supervisor/tests/supervisor/utils.rs
This PR clarifies recent changes to `Runtime` interface.
> Improve `Runtime` docs

- CHANGELOG.md
- exonum/src/api/backends/actix.rs
- exonum/src/api/manager.rs
- exonum/src/events/network.rs
- exonum/src/node/mod.rs
- test-suite/testkit/src/lib.rs
---
See: https://jira.bf.local/browse/ECR-3748
> Add HTTP server restart params into node config [ECR-3748]

- examples/cryptocurrency-advanced/backend/src/api.rs
- exonum/src/blockchain/mod.rs
- exonum/src/explorer/mod.rs
A little step against the technical debt.
> Remove TransactionMessage alias [ECR-3222]

- components/merkledb/src/access/extensions.rs
- components/merkledb/src/lib.rs
This PR updates MerkleDB docs to reflect the latest changes in it.
> Update MerkleDB docs

- .travis.yml
- exonum/benches/criterion/block.rs
Fix hanging in the `block` bench of the `exonum` crate.
> Fix `block` bench in main crate

- exonum/src/runtime/rust/service.rs
> Restore 1.36 compatibility

- .travis.yml
- exonum/src/runtime/types.rs
- test-suite/exonum-py-tests/setup.py
> Restore 1.36 compatibility with check in Travis CI

- CHANGELOG.md
- cli/Cargo.toml
- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/derive/Cargo.toml
- components/keys/Cargo.toml
- components/merkledb/Cargo.toml
- components/merkledb/README.md
- components/proto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency-advanced/cryptocurrency_advanced.yaml
- examples/cryptocurrency-advanced/docker/Dockerfile
- examples/cryptocurrency/Cargo.toml
- examples/sample_runtime/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- examples/timestamping/docker/Dockerfile
- examples/timestamping/timestamping.yaml
- exonum/Cargo.toml
- exonum/src/runtime/rust/mod.rs
- services/supervisor/Cargo.toml
- services/time/Cargo.toml
- services/time/README.md
- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
- test-suite/exonum-py-tests/exonum_tests/deploy.py
- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
- test-suite/testkit/Cargo.toml
- test-suite/testkit/README.md
- test-suite/testkit/server/Cargo.toml
0.13.0 Release Candidate 1 
---
> Release Candidate 1 0.13.0

- CHANGELOG.md
- cli/Cargo.toml
- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/derive/Cargo.toml
- components/keys/Cargo.toml
- components/merkledb/Cargo.toml
- components/merkledb/README.md
- components/proto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency-advanced/cryptocurrency_advanced.yaml
- examples/cryptocurrency-advanced/docker/Dockerfile
- examples/cryptocurrency/Cargo.toml
- examples/sample_runtime/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- examples/timestamping/docker/Dockerfile
- examples/timestamping/timestamping.yaml
- exonum/Cargo.toml
- exonum/build.rs
- services/supervisor/Cargo.toml
- services/time/Cargo.toml
- services/time/README.md
- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
- test-suite/exonum-py-tests/exonum_tests/deploy.py
- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
- test-suite/testkit/Cargo.toml
- test-suite/testkit/README.md
- test-suite/testkit/server/Cargo.toml
> Release Candidate 2 0.13.0

- exonum/src/blockchain/tests.rs
- exonum/src/runtime/dispatcher/error.rs
- exonum/src/runtime/dispatcher/tests.rs
- exonum/src/runtime/error.rs
- exonum/src/runtime/error/tests.rs
- exonum/src/runtime/mod.rs
- services/supervisor/tests/simple.rs
- services/supervisor/tests/supervisor/config.rs
- services/supervisor/tests/supervisor/main.rs
- services/time/tests/test_exonum_time.rs
- test-suite/testkit/src/api.rs
- test-suite/testkit/tests/interfaces/main.rs
Minor changes that didn't make it in #1585.
> Improve `ExecutionError` (finishing touches)

- test-suite/exonum-py-tests/exonum_tests/api.py
Add additional api tests for **blocks** endpoint (https://github.com/exonum/exonum-python-client/pull/48).
> Add additional api tests

- exonum/src/api/node/public/explorer.rs
- exonum/src/api/websocket.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/tests.rs
- exonum/src/node/consensus.rs
- exonum/src/runtime/dispatcher/mod.rs
- exonum/tests/websocket/main.rs
- test-suite/testkit/src/lib.rs
- test-suite/testkit/tests/counter/main.rs
Moved incorrect tx check to the explorer. Also added the same check in the websocket handle.
> Move incorrect tx check to the explorer [ECR-3907]

- .travis.yml
> Use rocksdb dependency from exonum apt source

- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
> Fix integration python tests

- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
> Proofread runtime docs

- .travis.yml
- components/merkledb/benches/encoding.rs
- components/merkledb/src/access/extensions.rs
- components/merkledb/src/access/mod.rs
- components/merkledb/src/backends/rocksdb.rs
- components/merkledb/src/db.rs
- components/merkledb/src/error.rs
- components/merkledb/src/hash.rs
- components/merkledb/src/lib.rs
- components/merkledb/src/proof_entry.rs
- components/merkledb/src/proof_list_index/mod.rs
- components/merkledb/src/proof_list_index/proof.rs
- components/merkledb/src/proof_map_index/key.rs
- components/merkledb/src/proof_map_index/mod.rs
- components/merkledb/src/validation.rs
- components/merkledb/src/views/address.rs
- components/merkledb/src/views/mod.rs
- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
This PR updates / improves MerkleDB documentation.
---
See: https://jira.bf.local/browse/ECR-4006
> Improve MerkleDB docs [ECR-4006]

- components/merkledb/src/access/mod.rs
- components/merkledb/src/map_index.rs
- components/merkledb/src/migration.rs
- components/merkledb/src/proof_map_index/mod.rs
- components/merkledb/src/proof_map_index/tests.rs
- components/merkledb/src/views/mod.rs
- components/merkledb/src/views/system_schema.rs
- components/merkledb/tests/components.rs
- exonum/src/runtime/dispatcher/schema.rs
This PR adds some `?Sized` bounds and removes some `<Q>`s.
> Fix unsized keys

- exonum/src/runtime/types.rs
> Fix typo in docstrings

- CHANGELOG.md
> Update changelog with breaking change

- exonum/src/proto/schema/exonum/ordered_map.proto
> Add an option to ordered_map proto file [ECR-4059]

- cli/tests/cli.rs
> Remove extern crate: cli [ECR-4004]

- components/build/src/lib.rs
- components/crypto/src/crypto_lib/sodiumoxide/x25519.rs
- components/crypto/src/lib.rs
- components/crypto/src/proto/mod.rs
- components/keys/src/lib.rs
- components/merkledb/src/error.rs
- components/merkledb/src/indexes/proof_list/mod.rs
- components/merkledb/src/indexes/proof_list/proof.rs
- components/merkledb/src/lib.rs
- components/merkledb/src/proto/mod.rs
- components/proto/src/lib.rs
Removed extern crate in components. 
Also, fixed order of use/mod.
> Remove extern crate: components [ECR-4004]

- examples/cryptocurrency-advanced/backend/src/lib.rs
- examples/cryptocurrency-advanced/backend/src/schema.rs
- examples/cryptocurrency-advanced/backend/src/transactions.rs
- examples/cryptocurrency-advanced/backend/src/wallet.rs
- examples/cryptocurrency/src/lib.rs
- examples/cryptocurrency/tests/api.rs
- examples/timestamping/backend/src/lib.rs
- examples/timestamping/backend/src/schema.rs
- examples/timestamping/backend/src/transactions.rs
Removed extern crate in examples.
Also, fixed order of use/mod.
> Remove extern crate: examples [ECR-4004]

- exonum/benches/criterion/block.rs
- exonum/benches/criterion/lib.rs
Removed extern crate in benches.
> Remove extern crate: benches [ECR-4004]

- test-suite/consensus-tests/tests/requests.rs
- test-suite/testkit/src/api.rs
- test-suite/testkit/src/lib.rs
- test-suite/testkit/src/server.rs
- test-suite/testkit/tests/inflating_currency/main.rs
- test-suite/testkit/tests/interfaces/main.rs
- test-suite/testkit/tests/runtime_api/main.rs
- test-suite/testkit/tests/service_hooks/main.rs
- test-suite/testkit/tests/system_api.rs
Removed extern crate in test-suite.
> Remove extern crate: test-suite [ECR-4004]

- services/time/README.md
- services/time/src/api.rs
- services/time/src/lib.rs
- services/time/src/schema.rs
- services/time/src/time_provider.rs
- services/time/src/transactions.rs
Removed extern crate in services.
> Remove extern crate: services [ECR-4004]

- test-suite/exonum-py-tests/exonum_tests/api.py
- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
Updated integration tests to actual versions of python infrastructure.
> Update integration tests to actual versions of python infrastructure [ECR-4069]

- exonum/src/api/node/mod.rs
- exonum/src/api/node/public/explorer.rs
In [this](https://github.com/exonum/exonum/pull/1615) PR, a bug with multiple connections to a websocket has been fixed. But, unfortunately, the solution turned out to be quite expensive in memory, since for each connection, in fact, a new instance of `Server` is created. This PR offers a solution to this problem by storing one `Server` instance that will handle all the connections.
---
> Optimize websocket broadcast server creation

- CHANGELOG.md
- components/merkledb/src/access/mod.rs
- components/merkledb/src/indexes/group.rs
- components/merkledb/src/lib.rs
- components/merkledb/src/migration.rs
- components/merkledb/src/views/address.rs
- components/merkledb/src/views/metadata.rs
- components/merkledb/src/views/mod.rs
Yet another approach to iteration over group keys as described by @popzxc [in this comment](https://github.com/exonum/exonum/pull/1637#discussion_r361319128).
Wishlist:
---
See: https://jira.bf.local/browse/ECR-3904
> Iterator over groups [ECR-3904]

- exonum/src/api/node/public/explorer.rs
- exonum/src/lib.rs
- exonum/src/runtime/error/tests.rs
- exonum/src/runtime/types.rs
Removed `extern crate serde_json` in exonum.
> Remove extern crate serde_json in exonum

- exonum/src/api/backends/actix.rs
- exonum/src/blockchain/block.rs
- exonum/src/blockchain/config.rs
- exonum/src/blockchain/schema.rs
- exonum/src/blockchain/tests.rs
- exonum/src/events/benches.rs
- exonum/src/events/internal.rs
- exonum/src/events/noise/tests.rs
- exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs
- exonum/src/events/tests.rs
- exonum/src/helpers/user_agent.rs
- exonum/src/lib.rs
- exonum/src/messages/signed.rs
- exonum/src/messages/tests.rs
- exonum/src/node/connect_list.rs
- exonum/src/proto/tests.rs
- exonum/src/runtime/blockchain_data.rs
- exonum/src/runtime/dispatcher/tests.rs
- exonum/src/runtime/error/tests.rs
- exonum/src/runtime/migrations.rs
- exonum/src/runtime/rust/stubs.rs
- exonum/src/runtime/rust/tests.rs
- exonum/src/runtime/types.rs
- exonum/src/runtime/versioning.rs
Removed `extern crate pretty_assertions` in exonum.
> Remove extern crate pretty_assertions in exonum

- LICENSE
- components/merkledb/Cargo.toml
- components/merkledb/LICENSE
- components/merkledb/src/backends/rocksdb.rs
- components/merkledb/src/backends/temporarydb.rs
- components/merkledb/src/indexes/group.rs
- components/merkledb/src/indexes/proof_list/proof_builder.rs
- components/merkledb/src/indexes/proof_map/proof_builder.rs
- components/merkledb/src/indexes/proof_map/tests.rs
- components/merkledb/src/lazy.rs
- components/merkledb/src/views/address.rs
- components/merkledb/src/views/system_schema.rs
- components/merkledb/tests/checkpoints.rs
- components/merkledb/tests/components.rs
- components/merkledb/tests/state_aggregation.rs
- cspell.sh
- examples/cryptocurrency-advanced/LICENSE
- examples/cryptocurrency/LICENSE
- examples/sample_runtime/LICENSE
- examples/timestamping/LICENSE
- exonum-dictionary.txt
- services/middleware/LICENSE
- services/supervisor/LICENSE
- services/time/LICENSE
- test-suite/testkit/LICENSE
- test-suite/testkit/server/test/index.js
- test-suite/testkit/server/test/service.js
- test-suite/testkit/server/test/testkit.js
---
See: https://jira.bf.local/browse/ECR-3848
> Use rust-rocksdb 0.13 [ECR-3848]

- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
Fix integration tests according to the latest python light client version.
> Fix integration tests

- components/merkledb/src/backends/rocksdb.rs
- components/merkledb/src/backends/temporarydb.rs
> Make the TemporaryDB more safety

- exonum/src/blockchain/schema.rs
This PR adds a bit more explanations for `Blockchain` schema.
> Clarify docs in Blockchain schema [ECR-4063] [ECR-4098]

- components/merkledb/src/views/metadata.rs
> Add IndexMetadata#identifier documentation

- CHANGELOG.md
- components/explorer/examples/explorer.rs
- components/explorer/src/api.rs
- components/explorer/src/lib.rs
- components/explorer/tests/explorer.rs
- services/explorer/tests/api.rs
- services/supervisor/tests/supervisor/main.rs
- test-suite/testkit/src/server.rs
- test-suite/testkit/tests/service_hooks/main.rs
---
See: https://jira.bf.local/browse/ECR-3914
> Rename the field content to message [ECR-3914]

- test-suite/exonum-py-tests/exonum_tests/api.py
> Fix an integration test according to new error responses

- ARCHITECTURE.md
- CONTRIBUTING.md
- README.md
- exonum-dictionary.txt
This PR updates the main README and architecture overview.
> Improve overall docs

- examples/cryptocurrency/examples/test.sh
> Fix an integration test according to new CommittedTransaction format

- components/explorer/src/lib.rs
---
See: https://jira.bf.local/browse/ECR-3911
> Clarify a description of the time field of the CommittedTransaction [ECR-3911]

- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
> Use the converter for address from the python client library

- components/system-api/Cargo.toml
- components/system-api/src/lib.rs
- components/system-api/src/private.rs
- components/system-api/src/public.rs
This PR adds a documentation for public and private REST API.
Note that doctests are still sometimes failing due to some bug (which, as occurs, was not really fixed by the recent PR).
> Document system API [ECR-4149]

- services/supervisor/src/api.rs
> Fix doctests

- components/merkledb/src/access/extensions.rs
> Fix error message in AccessExt::get_proof_entry

- examples/cryptocurrency-advanced/README.md
- examples/cryptocurrency-advanced/backend/src/api.rs
- examples/cryptocurrency-advanced/backend/src/lib.rs
- examples/cryptocurrency-advanced/backend/src/proto/service.proto
- examples/cryptocurrency-advanced/backend/src/schema.rs
- examples/cryptocurrency-advanced/backend/src/transactions.rs
- examples/cryptocurrency-advanced/backend/src/wallet.rs
- examples/cryptocurrency/src/lib.rs
This PR updates cryptocurrency examples. Complimentary to ECR-4023 and ECR-4178.
---
See: https://jira.bf.local/browse/ECR-4023, https://jira.bf.local/browse/ECR-4178
> Brush currency examples

- exonum/src/runtime/blockchain_data.rs
A small getter for easier implementation in EJB.
---
> Add BlockchainData::instance_name method

- cli/src/command/finalize.rs
- cli/src/command/generate_config.rs
- cli/src/config.rs
- cli/src/config_manager.rs
- cli/tests/cli.rs
- cli/tests/testdata/config/more_validators/cfg/0/node.toml
- cli/tests/testdata/config/more_validators/cfg/0/sec.toml
- cli/tests/testdata/config/more_validators/cfg/1/node.toml
- cli/tests/testdata/config/more_validators/cfg/1/sec.toml
- cli/tests/testdata/config/more_validators/cfg/2/node.toml
- cli/tests/testdata/config/more_validators/cfg/2/sec.toml
- cli/tests/testdata/config/more_validators/cfg/3/node.toml
- cli/tests/testdata/config/more_validators/cfg/3/sec.toml
- cli/tests/testdata/config/with_pass/cfg/0/node.toml
- cli/tests/testdata/config/with_pass/cfg/0/sec.toml
- cli/tests/testdata/config/without_pass/cfg/0/node.toml
- cli/tests/testdata/config/without_pass/cfg/0/sec.toml
- cli/tests/testdata/config/without_pass/cfg/1/node.toml
- cli/tests/testdata/config/without_pass/cfg/1/sec.toml
- cli/tests/testdata/config/without_pass/cfg/2/node.toml
- cli/tests/testdata/config/without_pass/cfg/2/sec.toml
- cli/tests/testdata/config/without_pass/cfg/3/node.toml
- cli/tests/testdata/config/without_pass/cfg/3/sec.toml
---
See: https://jira.bf.local/browse/ECR-4190
> Exclude itself from the connection list [ECR-4190]

- test-suite/exonum-py-tests/exonum_tests/__init__.py
- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
- test-suite/testkit/server/package.json
> Fix integration tests according to changes in protobuf structure

- .travis.yml
- components/keys/Cargo.toml
- components/keys/examples/key_generator.rs
- components/keys/exmples/key_generator.rs
- components/keys/src/lib.rs
- components/proto/src/lib.rs
- examples/timestamping/backend/Cargo.toml
- exonum/build.rs
---
See: https://jira.bf.local/browse/ECR-4251
> Added an utility for key generation from seed [ECR-4251]

- components/merkledb/src/hash.rs
- examples/cryptocurrency-advanced/backend/tests/api.rs
- exonum/src/blockchain/block.rs
- test-suite/testkit/tests/counter/counter.rs
- test-suite/testkit/tests/counter/main.rs
This PR introduces verification of `BlockProof`s and `IndexProof`s.
---
See: https://jira.bf.local/browse/ECR-4249
> Index proof verification [ECR-4249]

- CHANGELOG.md
- test-suite/testkit/src/lib.rs
- test-suite/testkit/tests/counter/counter.rs
- test-suite/testkit/tests/counter/main.rs
- test-suite/testkit/tests/service_hooks.rs
This PR modifies processing of incorrect transactions in the testkit and documents their processing in the crate docs.
---
See: https://jira.bf.local/browse/ECR-4244
> Clarify incorrect tx processing in testkit [ECR-4244]

- exonum/src/runtime/dispatcher/schema.rs
- exonum/src/runtime/types.rs
- services/supervisor/README.md
- services/supervisor/src/errors.rs
- services/supervisor/src/lib.rs
- services/supervisor/src/proto/service.proto
- services/supervisor/src/proto_structures.rs
- services/supervisor/src/transactions.rs
- services/supervisor/tests/supervisor/config.rs
- services/supervisor/tests/supervisor/main.rs
- services/supervisor/tests/supervisor/migrations/mod.rs
- services/supervisor/tests/supervisor/service_lifecycle.rs
This PR implements artifact unloading in the supervisor.
Based on commits from #1794; will be rebased after it is merged.
---
See: https://jira.bf.local/browse/ECR-4286, https://jira.bf.local/browse/ECR-4224
> Artifact unloading in supervisor [ECR-4286] [ECR-4224]

- CHANGELOG.md
- exonum/src/runtime/execution_context.rs
- exonum/src/runtime/mod.rs
This PR polishes documentation on artifact unloading. The counterpart in the doc repo is exonum/exonum-doc#412.
---
See: https://jira.bf.local/browse/ECR-4285
> Polish docs on artifact unloading [ECR-4285]

- examples/cryptocurrency-advanced/backend/examples/cryptocurrency-migration.rs
This PR (hopefully) fixes deploy tests which were accidentally borken after an upstream merge in #1801.
> Fix deploy tests

- CHANGELOG.md
- components/api/src/manager.rs
- exonum-node/Cargo.toml
- exonum-node/src/events/codec.rs
- exonum-node/src/lib.rs
- exonum-node/tests/node.rs
- test-suite/soak-tests/src/bin/toggle.rs
This PR updates changelog according to earlier changes in the async code and performs minor code changes.
> Brush up async code

- exonum/src/blockchain/block.rs
- exonum/src/proto/details/details.proto
- exonum/src/proto/schema/exonum/proofs.proto
- exonum/src/proto/schema/exonum/runtime/errors.proto
- exonum/src/runtime/error/mod.rs
> Add protobuf message for CallProof & make ExecutionErrorAux public [ECR-4364] [ECR-4365]

- CHANGELOG.md
- cli/src/command/run_dev.rs
- cli/tests/cli.rs
Subsequent runs with the same database are working now
---
> Fix run-dev command

- cspell.sh
- exonum-dictionary.txt
- test-suite/exonum-py-tests/exonum_tests/__init__.py
- test-suite/exonum-py-tests/exonum_tests/api.py
- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
- test-suite/exonum-py-tests/exonum_tests/deploy.py
- test-suite/exonum-py-tests/exonum_tests/migrate.py
- test-suite/exonum-py-tests/suite/common.py
- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
- test-suite/exonum-py-tests/suite/exonum.py
- test-suite/exonum-py-tests/suite/process_manager.py
---
See: https://jira.bf.local/browse/ECR-4283
> Add python tests for testing migration and unload logic [ECR-4283]

- cli/src/command/run_dev.rs
- examples/cryptocurrency-advanced/docker/Dockerfile
- examples/cryptocurrency-advanced/docker/launch.sh
- examples/timestamping/docker/Dockerfile
- examples/timestamping/docker/launch.sh
- test-suite/testkit/server/package-lock.json
- test-suite/testkit/server/package.json
> Use wildcard for allow origin in dev mode

- runtimes/rust/src/service.rs
> Fix wording:

- exonum/src/runtime/dispatcher/mod.rs
This PR improves logging of service lifecycle in the core crate.
---
See: https://jira.bf.local/browse/ECR-4384
> Improve logging of service lifecycle [ECR-4384]

- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/merkledb/Cargo.toml
- components/proto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum-node/Cargo.toml
- exonum/Cargo.toml
- runtimes/rust/Cargo.toml
- services/middleware/Cargo.toml
- services/supervisor/Cargo.toml
- services/time/Cargo.toml
- test-suite/rust-runtime-proto/Cargo.toml
> Bump exonum-build version up to 1.0.1 [ECR-4386]

- components/merkledb/src/db.rs
- components/merkledb/src/views/tests.rs
This PR documents intended merge workflow for `Database` and possible logical errors if this workflow is not followed.
---
See: https://jira.bf.local/browse/ECR-2046
> Document merge workflow [ECR-2046]

- .travis.yml
- components/merkledb/Cargo.toml
- components/merkledb/src/backends/rocksdb.rs
> Bump rocksdb version up to 0.14.0

- test-suite/exonum-py-tests/exonum_tests/deploy.py
- test-suite/exonum-py-tests/exonum_tests/migrate.py
> Some changes in python tests according changes in launcher

- components/crypto/Cargo.toml
- components/merkledb/Cargo.toml
- components/proto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum-node/Cargo.toml
- exonum/Cargo.toml
- runtimes/rust/Cargo.toml
- services/middleware/Cargo.toml
- services/supervisor/Cargo.toml
- services/time/Cargo.toml
- test-suite/exonum-py-tests/exonum_tests/api.py
- test-suite/exonum-py-tests/exonum_tests/crypto_advanced.py
- test-suite/exonum-py-tests/exonum_tests/deploy.py
- test-suite/exonum-py-tests/exonum_tests/migrate.py
- test-suite/exonum-py-tests/suite/common.py
- test-suite/exonum-py-tests/suite/crypto_advanced_client.py
- test-suite/exonum-py-tests/suite/exonum.py
- test-suite/exonum-py-tests/suite/process_manager.py
- test-suite/rust-runtime-proto/Cargo.toml
- test-suite/testkit/Cargo.toml
> Handle ConnectionError exception in the python tests

- .github/workflows/rust.yml
---
See: https://jira.bf.local/browse/ECR-4397
> Add Github Actions workflow for building on windows host [ECR-4397]

- .github/workflows/rust.yml
- .travis.yml
> Add job for a testing doc-tests in the actions CI

- .travis.yml
---
See: https://jira.bf.local/browse/ECR-4407
> Increase a number of the tests for coverage check [ECR-4407]

- .travis.yml
- README.md
- components/api/Cargo.toml
- components/build/Cargo.toml
- components/crypto/Cargo.toml
- components/explorer/Cargo.toml
- components/keys/Cargo.toml
- components/merkledb/Cargo.toml
- components/proto/Cargo.toml
- components/system-api/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/sample_runtime/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum-node/Cargo.toml
- exonum-node/src/state.rs
- exonum/Cargo.toml
- runtimes/rust/Cargo.toml
- services/explorer/Cargo.toml
- services/middleware/Cargo.toml
- services/supervisor/Cargo.toml
- services/time/Cargo.toml
- services/time/src/schema.rs
- test-suite/testkit/Cargo.toml
- test-suite/testkit/README.md
- test-suite/testkit/src/api.rs
> Bump rust from 1.45.2 to 1.46.0 and update dependencies

- test-suite/testkit/server/package-lock.json
- test-suite/testkit/server/package.json
> Update exonum-client up to 0.18.4

- .github/workflows/ci.yml
- .github/workflows/integration.yml
- exonum/src/runtime/dispatcher/migration_tests.rs
---
See: https://jira.bf.local/browse/ECR-4432
> Add integration tests in Github Actions [ECR-4432]

- .github/workflows/ci.yml
- cli/tests/cli.rs
- examples/cryptocurrency-advanced/frontend/package-lock.json
- examples/timestamping/frontend/package-lock.json
> Fix installing llvm and clang on windows in CI
