- exonum/src/blockchain/tests.rs
- exonum/src/encoding/spec.rs
- exonum/src/explorer/mod.rs
Based on https://github.com/exonum/exonum/pull/278
Closes https://github.com/exonum/exonum/issues/279
> Make fields public

- exonum/src/events/network.rs
Closes https://github.com/exonum/exonum/issues/73
With `PollOpt::edge()` mio could ignore connection events, if they appear in one short period.
https://carllerche.github.io/mio/mio/struct.Poll.html#edge-triggered-and-level-triggered
> Fix Network discover failure

- exonum/src/storage/proof_map_index/key.rs
- exonum/src/storage/proof_map_index/mod.rs
Currently `DBKey` is already exposed through `MapProof` enum:
```rust
pub enum MapProof<V> {
/// A boundary case with a single element tree and a matching key.
LeafRootInclusive(DBKey, V),
/// A boundary case with a single element tree and a non-matching key
LeafRootExclusive(DBKey, Hash),
/// A boundary case with empty tree.
Empty,
/// A root branch of the tree.
Branch(BranchProofNode<V>),
}
```
> Make DBKey public

- .travis.yml
- exonum/src/storage/entry.rs
- exonum/src/storage/mod.rs
- exonum/src/storage/proof_map_index/mod.rs
Still we need https://github.com/deadlinks/cargo-deadlinks/issues/1 to be fixed for the correct usage.
> Integrate dead links check into travis script

- .travis.yml
This changes adds profiler into travis "clippy" build, and makes build run with `--verbose`.
For now it should fail, until https://github.com/exonum/exonum/pull/338 will be merged.
> Add profiler into build, make build verbose

- CHANGELOG.md
- exonum/src/blockchain/service.rs
...and provide implementation tip for transactions created with the `message!` macro.
Closes #343 (together with PRs to other repos).
> Clarify `Transaction.info()` usage

- exonum/src/crypto.rs
This PR improves the debug formatting of crypto types. Presently, a type can be output as less than 8 hex digits:
```rust
let hash = Hash::new([1; 32]);
println!("{:?}", hash); // would output `Hash(1111)`
```
This can lead to ambiguities (e.g., what's the first byte of `Hash(1FFFFFF)`? Could be either `01` or `1F`) and overall looks slightly weird. This PR amends this behavior to always output 2 hex digits for each byte.
**PS:** Is it intentional that "private" and "public" wrappers have differing formats, with "private" serialized like `SecretKey(80808080...)` and "public" as `PublicKey(80808080)`? If this is not an intentional choice, I suppose they could be unified within this PR as well.
> Fix debug formatting for crypto types

- exonum/src/events/tests.rs
Fixed a problem in `test_network_reconnect` 
Our assumption was that `DisconnectWithPeer` event is processed synchronized.
But if reconnect time is small enough, it's possible that we already disconnect and reconnect to peer, and only after this starting to process `DisconnectWithPeer`.
This cause to disconnect just after reconnect. And double "`Connect` message" processing.
In real code, the time between disconnect and reconnect is significant, and this case could be ignored.
Another reason to ignore this, is that it is a valid case to process double "`Connect` message".
Closes: https://github.com/exonum/exonum/issues/354
> Fix network reconnect test

- .travis.yml
This change, use travis `fast_finish` option for `non-fatal-checks`. This should make check a bit faster.
> Make non-fatal-checks async.

- CHANGELOG.md
- exonum/src/helpers/fabric/details.rs
Allow creating auditor from command line. For now you can just ommit public key of some node in `finalize` command, and this node will be handled as auditor.
Allow set public-api during config finalization phase. The sintax same as in `run` command.
Tested on anchoring and configuration serivces.
> Allow creating auditor from command line.

- CHANGELOG.md
- exonum/src/helpers/fabric/clap_backend.rs
In new version rustc/clap `crate_authors!` can not return static string.
> Fix crate_authors! macro usage

- .travis.yml
`0.3.0` version supports `-V` (`--version`) flag, so  it will not be installed every time.
> Update cargo-deadlinks version (0.3.0)

- exonum/src/helpers/fabric/details.rs
Listener config was override by runtime flag.
> Fixed api listener config

- CHANGELOG.md
- exonum/src/helpers/fabric/details.rs
I'm not sure how many details of underlying database the user should now, but I like a more generic interface, because it will give us more possibilities to change the implementation without additional "breaking changes".
Opinions?
> Change "rocksdb" commandline parameter to a more generic "database"

- exonum/src/helpers/fabric/clap_backend.rs
https://docs.rs/clap/2.28.0/clap/enum.AppSettings.html#variant.ArgRequiredElseHelp seems to do the trick.
Closes https://github.com/exonum/exonum/issues/389
> ClapBackend: Show a help message when there're no args

- CHANGELOG.md
- exonum/src/blockchain/service.rs
- exonum/tests/node.rs
- sandbox/src/sandbox.rs
Motivation: default implementation can confuse users. Implementing `Service` trait it is easily to forget about `state_hash` method because it is already implemented. Without the default implementation user will get a compilation error and and this will force him look at the documentation.
Disadvantages: minimal service code becomes a little more "bloated".
> Remove default 'state_hash' implementation

- CHANGELOG.md
- exonum/src/api/mod.rs
- exonum/src/api/public/system.rs
- exonum/src/blockchain/service.rs
- exonum/src/encoding/serialize/json.rs
- exonum/src/encoding/spec.rs
- exonum/src/explorer/mod.rs
- exonum/src/messages/spec.rs
Removes `Transaction::info`.
Makes `Transaction` inherit `ExonumJson`. 
We can test api. For example: result of `curl http://127.0.0.1:8000/api/system/v1/transactions/44c6c2c58eaab71f8d627d75ca72f244289bc84586a7fb42186a676b2ec4626b`
looks unchanged.
> Refactor `Transaction::info` method

- exonum/src/events/mod.rs
- exonum/src/node/events.rs
- exonum/src/node/mod.rs
- sandbox/src/sandbox.rs
exonum use `futures::sync::mpsc::channel` for sending events from main event-loop thread into workers threads.
`Sender` for this channel is async by default, which means that sending data produce new `Future`. Keeping this `Sender`s in synchronised code forces developer to `clone` `Sender`'s `Sink` and finalize sending with `.wait`. 
Usually code looks like:
```
sender.clone().send(request).wait().log_err() // .clone() and .wait() there redurant.
```
In code like this it's easy to forgot `wait` after send.
Additionally this leads to inner mutability, which is an implicit, that makes api worsen.
In this pull request: `Sender` replaced by `SyncSender` which designed especially for this kind of synchronisation, but this change introduce some code duplication, to fulfit borrow checker rules.
> Remove inner mutability in channels usage

- CHANGELOG.md
- exonum/src/api/public/mod.rs
- exonum/src/api/public/system.rs
- exonum/src/node/mod.rs
(A stripped-down version of https://github.com/exonum/exonum/pull/401)
We need to check the node is alive. It's suitable to have a public endpoint with healthcheck status.
Usage example:
```text
$ curl http://127.0.0.1:8200/api/system/v1/healthcheck                                                                                                                                   
{                                                                                                                                                                                        
"status": false                                                                                                                                                                        
} …
```
> Basic healthcheck endpoint

- exonum/src/api/private/system.rs
- exonum/src/api/public/blockhain_explorer.rs
- exonum/src/api/public/system.rs
See https://github.com/exonum/exonum/pull/405#discussion_r158683937
> @DarkEld3r:
> Maybe self_ instead of _self? Underscore prefix suppresses "unused variable" warning.
--
> `_self` -> `self_`

- exonum/src/storage/proof_map_index/key.rs
This PR restores pre existing tests for the `DBKey`.
> Restore DBKey tests

- exonum/src/encoding/serialize/mod.rs
Here's the corresponding declaration: https://github.com/exonum/exonum/blob/e66158647b3c21919c2c5bc99d4388f1b77f7db4/exonum/src/encoding/serialize/json.rs#L69.
It's interesting that I've faced the bug when trying to upgrade btc-anchoring to new exonum.
Debugging this error from macro from macro from a patched crate was fun, but time consuming :) 
```
error[E0053]: method `serialize_field` has an incompatible type for trait
--> src/details/btc/transactions.rs:97:1
|
97 | implement_tx_wrapper! {FundingTx}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| |
| expected trait `iron::Error + std::marker::Send + std::marker::Sync`, found trait `iron::Error`
| in this macro invocation
|
= note: expected type `fn(&details::btc::transactions::FundingTx) -> std::result::Result<serde_json::Value, …
```
> Fix implement_exonum_serializer! to match ExonumJson

- exonum/src/helpers/fabric/builder.rs
- exonum/src/helpers/fabric/context_key.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/fabric/mod.rs
So this was born out of https://github.com/exonum/exonum/pull/416#issuecomment-356197978.
The plan to add `Context::service_config` is not perfect, because context can very well lack `service_config` at all. I think what we really want here is something like this:
```Rust
pub trait ServiceFactory: 'static {
#[allow(unused_variables)]
fn command(&mut self, command: CommandName) -> Option<Box<CommandExtension>>;
fn make_service(&mut self, run_context: &Context) -> Box<Service>;
}
pub trait ServiceFactoryWithConfig: ServiceFactory {
type Config;
fn make_service(&mut self, run_context: &Context, config: Self::Config) -> Box<Service>;
}
```
This is probably doable, and even in a nice way, despite the problem of object-safe associated types (which I believe is surmountable in a nice way by …
> Introduce strongly-typed Context keys

- CHANGELOG.md
- exonum/src/messages/raw.rs
- exonum/src/messages/spec.rs
- exonum/src/messages/tests.rs
While working on the `protocol!` macro, I've noticed that we use inherent associated functions for constructing transactions. I think putting this function inside the `Message` trait is more natural, and allows to work with messages generically. 
This is a breaking change, because the users will have to add `use exonum::encoding::Message` to use `from_raw`. If we want, we can provide an inherent method with the same name for backwards compatibility, but I'd rather not do this.
> Make `from_raw` method generic

- exonum/src/lib.rs
- exonum/src/storage/proof_map_index/key.rs
Field offsets [are now calculating automatically](https://github.com/exonum/exonum/pull/413), so we (probably) don't need to allow zero prefixed literals.
> Remove 'allow(zero_prefixed_literal)' attribute

- exonum/src/node/mod.rs
While trying to come up with a test for CORS functionality, I've found out that testkit and exonum duplicate code for creating andpoints, and that testkit does not use CORS middleware because of it. As a solution to this problem, this PR suggest to extract this functionality into `pub` but `doc(hidden)` functions. So now we can be sure that testkit provides the same API structure as Exonum. On the other hand, now it would be harder to tweak API for testkit, but hopefully we won't need such tweaks?
I've mechanically extracted all dependencies to function parameters, so someone should look at this as a whole and check that API makes sense. 
The testkit side of things is https://github.com/exonum/exonum-testkit/pull/23
> Expose api handler creation fucntions for testing

- .travis.yml
- exonum/src/encoding/float.rs
Both positive and negative values has the same `classify` representation (`FpCategory::Zero`), which can make possible problems while encoding/decoding floats.
This change fixes behavior by forbidding negative zeros in wrappers' constructors.
cc @matklad @vldm @DarkEld3r
> Encoding: Properly handling float serialization of zero values

- CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/storage/db.rs
- exonum/src/storage/memorydb.rs
- exonum/src/storage/rocksdb.rs
- sandbox/examples/merkle_map.rs
This is just a refactoring to make `Databases` trait easier to implement correctly, and to make a bug, which was almost introduced in #421, impossible. 
* Remove `clone` method from the `Database` trait.
* Store `Arc<Database>` instead of `Box<Database>` in `Blockchain` (this also should make cloning the blockchain faster, because it removes an allocation).
* Change `merge` signature from `&mut self` to `&self` which is semantically more clear.
> Database trait simplification

- exonum/src/blockchain/config.rs
- exonum/src/events/codec.rs
- exonum/src/events/network.rs
- exonum/src/events/tests.rs
- exonum/src/node/mod.rs
- exonum/tests/testdata/config/config01.toml
- exonum/tests/testdata/config/config02.toml
- exonum/tests/testdata/config/config03.toml
- exonum/tests/testdata/config/config04.toml
- exonum/tests/testdata/config/config0_pub.toml
- exonum/tests/testdata/config/config12.toml
- exonum/tests/testdata/config/config13.toml
- exonum/tests/testdata/config/config14.toml
- exonum/tests/testdata/config/config1_pub.toml
- exonum/tests/testdata/config/config23.toml
- exonum/tests/testdata/config/config24.toml
- exonum/tests/testdata/config/config2_pub.toml
- exonum/tests/testdata/config/config34.toml
- exonum/tests/testdata/config/config3_pub.toml
- exonum/tests/testdata/config/template.toml
- sandbox/src/sandbox.rs
This PR makes `MAX_MESSAGE_LEN` configurable, so we get rid of this hardcoded const.
~~**Important note.**
I had to duplicate this parameter in both configs: `ConsensusConfig` and `NetworkConfiguration`. The latter doesn't (de)serialize it, so we actually store it only in `genesis.consensus` section (as all nodes must share this value). This tricky workflow is needed for convenient passing it to `MessagesCodec`.~~
> Make MAX_MESSAGE_LEN configurable

- exonum/src/helpers/fabric/builder.rs
- exonum/src/helpers/fabric/clap_backend.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/fabric/internal.rs
- exonum/src/helpers/fabric/mod.rs
- exonum/tests/config.rs
Implements `run-dev` mode for running node without configuring.
- `run-dev` command is added
- `commands` vector of `NodeBuilder` is refactored to `HashMap` (maybe `BTreeMap` would be better?)
- command `execute` function now accepts the list of the commands (the aforementioned `HashMap`) in order to execute other subcommands for generating configs. I don't like this solution, it was the first straightforward way that came to my mind
- `Context` args setters were added. That's rather a crutch than a cool solution. (The problem is that the commands called inside `RunDev` depend on these args.) 
Using `run-dev` command
> Run dev mode

- exonum/src/storage/db.rs
- exonum/src/storage/memorydb.rs
- exonum/src/storage/tests.rs
This PR removes unnecessary mutability regarding `Database`, which happened due to #422. For some reason, it isn't picked up by `clippy`, although corresponding warnings *are* output by the compiler. Additionally, `Database` docs are updated to avoid similar mistakes in the future.
Other (fixes Rust compiler warning).
By looking at compilation results (e.g., in the Travis log): they should no longer contain warnings from the Rust compiler.
> Remove unneeded mutability

- CHANGELOG.md
- exonum/src/storage/keys.rs
This PR changes the `StorageKey` implementation for signed integer types in order to order them in the natural order. Previously, these type were encoded in big-endian, which means that say `-1i8` (encoded as `0xff`) was considered greater than `127i8` (encoded as `0x7f`).
After the change, the signed integer value is shifted to the range of the corresponding signed integer. It's easy to see that this is the *only* way to order signed ints in the natural order without increasing the size of allocated bytes for the int.
Technically, this is a breaking change. However, I'm having doubts anyone has used `StorageKey` for signed ints because of the unnatural sorting order. Obviously, this needs to be discussed further.
There are unit tests included into the PR. Maybe, it could make sense to …
> Storage key for signed ints

- CHANGELOG.md
- exonum/benches/block.rs
- exonum/src/blockchain/config.rs
- exonum/src/blockchain/schema.rs
- exonum/src/blockchain/tests.rs
- exonum/src/crypto.rs
- exonum/src/encoding/spec.rs
- exonum/src/messages/raw.rs
- exonum/src/messages/spec.rs
- exonum/src/node/consensus.rs
- exonum/src/node/state.rs
- exonum/src/storage/proof_list_index/tests.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/src/storage/proof_map_index/node.rs
- exonum/src/storage/sparse_list_index.rs
- exonum/src/storage/values.rs
- sandbox/src/sandbox.rs
- sandbox/src/sandbox_tests_helper.rs
- sandbox/tests/consensus.rs
- sandbox/tests/old.rs
A **refactoring** PR.
Problem:
`Message::hash` and `StorageValue::hash` are two different functions which must behave the same nonetheless, which introduces a non-trivial invariant into the code. 
Solution:
Extract `hash` method to a separate small trait and use it everywhere. 
Questions:
- What is the best name for this trait? The natural choice is `Hash`, but it clashes both with the `Hash` struct and with `std::hash::Hash`. Another alternative is `Digest`, but it doesn't match the `fn hash` name. And changing `fn hash` to `fn digest` requires a much larger diff, and `fn hash(&self) -> Hash` reads better than `fn digest(&self) -> Hash`. My preferred solution is to use the current `CryptoHash`.
- Quite a few types implement an inherent version of the `hash` method (for example, all of …
> Introduce CryptoHash trait

- exonum/src/blockchain/mod.rs
- exonum/src/encoding/spec.rs
- exonum/src/node/mod.rs
A **refactoring** RP. Follow up upon #442: remove inherent impl from `encoding_struuct`, which is covered by `trait CryptoHash` anyway. 
I believe the changes here covered by changelog entry for #422.
> Don't add inherent `hash` method in encoding_struct!

- exonum/CHANGELOG.md
- exonum/src/encoding/float.rs
This fix will allow to use `Vec<F32>` and `Vec<F64>` in `message!` macros.
> [Fix] Implement ExonumJsonDeserialize for floats

- Cargo.toml
`cargo test` in the root equivalent to `cargo test --all` which tries to build
all members of the workspace. However, 3rdparty crates are totally optional and
don't work with stable, so let's exclude them.
> Make `cargo test` work on stable

- .github/ISSUE_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE.md
- .markdownlintrc
- .travis.yml
- CONTRIBUTING.md
- INSTALL.md
- README.md
- exonum/CHANGELOG.md
- exonum/README.md
- testkit/CHANGELOG.md
- testkit/README.md
This PR adds [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) pass to travis builds.
[Initial list of warnings](https://gist.github.com/anonymous/923155c83e6a2c7f9470fc9d8f4969c0) (before any fixes)
Most of the warnings were fixed, though some were disabled through the config as not fitting to our use case:
- no-duplicate-header - causes problems in changelogs
- first-header-h1 and first-line-h1 - cause problems with issue/PR templates
The linter is lauched using the following command:
`find . -not -path "./3rdparty/*" -name "*.md" | xargs markdownlint --config .markdownlintrc`
`./3rdparty` directory is ignored.
> markdownlint [ECR-427]

- .travis.yml
- README.md
Let's pin a specific version of Rust, so that we *know* which is the minimal supported version.
> Specify Rust version for CI explicitelly

- .travis.yml
```text
$ cargo deadlinks --dir target/doc
Linked file at path /home/travis/build/exonum/exonum/target/doc/exonum/encoding/serialize/trait.Serialize.html does not exist!
```
I don't see an easy way to fix the error itself (as it comes from relative paths in serde's docs + reexporting of these types in our code) so it seems easier to ignore it for now. `cargo-deadlinks` has no built-in functionality for ignoring certain warnings, but we can just create a dummy page.
> Add a hack to ignore a warning from cargo-deadlinks [ECR-445]

- exonum-dictionary.txt
- exonum/CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/api/mod.rs
- exonum/src/api/private/system.rs
- exonum/src/api/public/blockchain_explorer.rs
- exonum/src/api/public/system.rs
- exonum/src/explorer/mod.rs
- exonum/src/helpers/config.rs
- exonum/src/helpers/fabric/internal.rs
- exonum/src/helpers/fabric/mod.rs
- exonum/src/helpers/types.rs
- exonum/src/lib.rs
- exonum/src/storage/error.rs
- exonum/src/storage/rocksdb.rs
- services/configuration/src/config_api.rs
- testkit/tests/counter/counter.rs
- testkit/tests/currency/cryptocurrency.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
This switches error handling from `std::Error` to the [`failure`](https://github.com/withoutboats/failure) crate.
How to use failure (abridged edition):
- use `failure::Error` instead of `Box<Error>`,
- to define an error, add `derive(Fail)` to a struct/enum. Consider adding `#[cause]` and `#[fail(display="format")` attributes,
- consider using `.context` method to improve error messages for enduser-visible expected errors.
Here's the high-level list of changes in the PR:
1) `storage::Error` implements `Fail` (I've also changed the naming inside storage module to `module::Item` style)
2) The `fabric` module uses `failure::Error` instead of `Box<Error>`. This is a breaking change. We also should get slightly better error messages when reading config fails due to IO errors (message now …
> Use failure for error handling

- exonum/src/encoding/mod.rs
I propose to remove the comment at all: "TODO" are ugly and we are waiting for a new format anyway.
> Remove TODO comment [ECR-588]

- exonum/CHANGELOG.md
- exonum/src/blockchain/service.rs
- exonum/tests/node.rs
- sandbox/src/config_updater.rs
- sandbox/src/sandbox.rs
- sandbox/src/timestamping.rs
- services/time/examples/simple_service.rs
- services/time/src/lib.rs
- testkit/examples/timestamping.rs
- testkit/src/lib.rs
- testkit/tests/counter/counter.rs
- testkit/tests/currency/cryptocurrency.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
- testkit/tests/service_hooks/hooks.rs
[#EEN-182]
The value returned from the `Service::service_name` method is not stored anywhere, so there is no need for such a strict bound.
With such a strict restriction, there is no way to use the values produced at run-time (frankly, it is still possible to use a mutable `static`, but this doesn't cover all scenarios).
> Removed the `'static` bound from the `Service::service_name` result. [EEN-182]

- .circleci/config.yml
- .travis.yml
- exonum/src/blockchain/mod.rs
- services/configuration/src/api.rs
This PR returns missing `-D warnings` argument for clippy, and denies warnings from the Rust compiler as well.
> Make CI stricter

- testkit/CHANGELOG.md
- testkit/src/lib.rs
- testkit/tests/counter/main.rs
This PR fixes problem with signature of `TestKitApi::send` method, which previosly did not accept `Box<Transaction>`.
> Fix `TestKitApi::send` signature

- exonum/src/api/public/blockchain_explorer.rs
- exonum/src/explorer/mod.rs
- testkit/tests/counter/counter.rs
- testkit/tests/counter/main.rs
This PR fixes the format of transaction information returned by the blockchain explorer, to use `"type": "unknown" | "in-pool" | "committed"` tag instead of returning data like `{ "in-pool": { "content": ... } }`.
> Fix `TransactionInfo` JSON serialization

- exonum/src/blockchain/service.rs
- exonum/src/encoding/mod.rs
- exonum/src/messages/raw.rs
- exonum/src/node/state.rs
- exonum/src/storage/base_index.rs
- exonum/src/storage/entry.rs
- exonum/src/storage/key_set_index.rs
- exonum/src/storage/list_index.rs
- exonum/src/storage/map_index.rs
- exonum/src/storage/proof_list_index/mod.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/src/storage/sparse_list_index.rs
- exonum/src/storage/value_set_index.rs
This PR prepares exonum for https://github.com/rust-lang/rust/pull/48274.
Example of fixed warnings: https://travis-ci.org/exonum/exonum/jobs/339060721#L791
> Fix hoedown/pulldown cargo-doc warnings [ECR-687]

- exonum-dictionary.txt
- exonum/CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/helpers/mod.rs
- exonum/src/lib.rs
Use `rfc2822` for time formatting and also reduce visual noise.
Also this PR will break the benchmark scripts.
Here example of a new output:
> Make log output more human readable

- README.md
See https://github.com/exonum/exonum/pull/517#discussion_r170247779:
> https://img.shields.io/circleci/project/github/exonum/exonum.svg
> looks like we display the latest status of any build, not necessary of master branch.
> Make circleci's badge show only master branch status [ECR-815]

- services/configuration/CHANGELOG.md
- services/configuration/src/transactions.rs
This PR cleans up some mistakes in #496, such as incorrect documentation of transactions. It also provides the changelog.
The documentation errors was noticed by [the `deadlinks` lint](https://travis-ci.org/exonum/exonum/jobs/344503829#L1732). Unfortunately, it seems that the documentation for `Option::as_ref` method (mentioned on the `MaybeVote` page because it implements `Deref<Target = Option<Vote>>`) is copied verbatim from the `std` docs, which leads to 3 more incorrect links discovered by `deadlinks`. Honestly, I don't know how to best fix this.
I can't help but notice that the changelog does not describe #481 (and possibly other changes as well). Should I include them as well, or will they be dealt with separately?
> Clean up after #496

- .travis.yml
We don't actually need to cache it, because sandbox is in the workspace, right?
> .travis.yml: Remove sandbox/target from cache

- exonum/CHANGELOG.md
- exonum/src/api/public/blockchain_explorer.rs
- exonum/src/api/public/mod.rs
This enum is useful for `testkit` and other purposes.
> Make TransactionInfo public

- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/api/mod.rs
- exonum/src/api/private/system.rs
- exonum/src/lib.rs
This PR employs `bodyparser` crate for parsing data sections of POST-requests.
Motivation: https://github.com/exonum/exonum/pull/446/files#r166044729
Should I add a changelog item?
> Employ 'bodyparser' crate [ECR-688]

- exonum/src/blockchain/config.rs
- exonum/src/events/tests.rs
> Rename DEFAULT_MAX_MESSAGE_LEN constant

- CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/src/storage/proof_list_index/mod.rs
- exonum/src/storage/proof_list_index/proof.rs
- exonum/src/storage/proof_list_index/tests.rs
- exonum/src/storage/proof_map_index/mod.rs
- exonum/src/storage/proof_map_index/proof.rs
- exonum/src/storage/proof_map_index/tests.rs
- sandbox/src/sandbox.rs
- sandbox/src/sandbox_tests_helper.rs
- sandbox/tests/consensus.rs
- services/configuration/src/schema.rs
- services/configuration/src/transactions.rs
- services/time/examples/simple_service.rs
- services/time/src/lib.rs
Personally, I prefer a more concise naming: `merkle_root`, but `merkle_root_hash` can be more descriptive.
> Rename 'root_hash' to 'merkle_root' [ECR-767]

- .travis.yml
- exonum/src/blockchain/mod.rs
- exonum/src/encoding/mod.rs
- exonum/src/encoding/spec.rs
- exonum/src/storage/values.rs
There's no point in having `cargo-deadlinks` as a non-fatal check - everyone just ignores it.
This PR fixes some of the warnings.
Though, there're some bugs in `rustdoc`, so a few more hacks were added to suppress them for now.
```
https://docs.rs/exonum-configuration/0.6.0/exonum_configuration/struct.MaybeVote.html
Linked file at path /home/ozkriff/bitfury/exonum/target/std/string/struct.String.html does not exist!
Linked file at path /home/ozkriff/bitfury/exonum/target/std/primitive.usize.html does not exist!
Linked file at path /home/ozkriff/bitfury/exonum/target/doc/exonum_configuration/enum.Option.html does not exist!
```
> travis: Remove non-fatal-checks, move cargo-deadlinks to 'lints' job [ECR-822]

- CHANGELOG.md
- exonum/benches/block.rs
- exonum/src/api/public/blockchain_explorer.rs
- exonum/src/api/public/system.rs
- exonum/src/api/tests.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/src/blockchain/tests.rs
- exonum/src/blockchain/transaction.rs
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/node/requests.rs
- exonum/src/node/state.rs
- sandbox/src/sandbox.rs
- sandbox/src/sandbox_tests_helper.rs
- services/configuration/src/tests/api.rs
- testkit/src/api.rs
- testkit/src/lib.rs
- testkit/tests/counter/counter.rs
- testkit/tests/counter/main.rs
- testkit/tests/service_hooks/hooks.rs
- testkit/tests/service_hooks/main.rs
Save transactions in persistent pool instead of in memory `Map`. This allows node to recover safe after restart.
> Change mempool to save transactions in storage. [ECR-895]

- .travis.yml
- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/blockchain/tests.rs
- exonum/src/encoding/fields.rs
- exonum/src/encoding/serialize/json.rs
- exonum/src/encoding/tests.rs
- exonum/src/events/tests.rs
- exonum/src/messages/protocol.rs
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/storage/keys.rs
- exonum/src/storage/values.rs
- sandbox/src/sandbox.rs
- sandbox/src/sandbox_tests_helper.rs
- sandbox/tests/consensus.rs
- sandbox/tests/old.rs
- services/time/Cargo.toml
- services/time/examples/simple_service.rs
- services/time/src/lib.rs
- services/time/tests/test_exonum_time.rs
- testkit/src/network.rs
-> What happen?
Rewriting `exonum-time` from `SystemTime` to `chrono::DateTime`. `SystemTime` can't be used in storages and messages anymore, but it's still in use in ~~dark and scary~~ some internals (no, we can't rewrite those places to `chrono`, because ~~I tried and it's complete nightmare~~ `tokio` and a lot of different things are tangled with `SystemTime` and `chrono` is not that usable in some scenarios). 
-> Drawbacks?
As a drawback, there're a lot of `into` calls in the code related to time operations, but personally I don't think it's huge problem.
-> For what? I loved `SystemTime`!
We've found some weird behavior in one of the tests under Windows. After short investigation we've released that `SystemTime` has different precision and (it's more important) different ranges on …
> Rewrite to chrono::DateTime [ECR-821]

- CHANGELOG.md
- exonum/src/crypto.rs
- exonum/src/storage/hash.rs
- exonum/src/storage/mod.rs
- exonum/src/storage/values.rs
A slightly different approach to the "`CryptoHash` implementation for `Hash`" [problem](https://github.com/exonum/exonum/pull/562):
- `CryptoHash` is no longer implemented for `Hash`.
- `UniqueHash` trait is introduced.
- Storage uses `UniqueHash` instead of `CryptoHash`.
> UniqueHash trait

- examples/cryptocurrency/src/lib.rs
Hello,
while I was studying the example I noticed that `wallet` is evaluated in block.
I am not sure but it seems like there is no any special reason for that. So, I tried to remove the block and everything still worked fine.
Please, correct me if I am wrong here.
> example: Don't evaluate wallet in block

- examples/cryptocurrency/src/lib.rs
- examples/cryptocurrency/tests/api.rs
Replacement for https://github.com/exonum/exonum/pull/573
There is no way to test `TxCreateWallet`, as exonum will prevent from processing the same transaction twice.
> Human readable failures in cryptocurrency example

- testkit/src/checkpoint_db.rs
- testkit/src/lib.rs
- testkit/tests/change_configuration.rs
- testkit/tests/inflating_currency/main.rs
Note: this is remake of https://github.com/exonum/exonum/pull/569 which was closed due to local technical difficulties.
This PR changes the interface of CheckpointDb from merge based rollbacks to  rollbacks to handmade checkpoints. Multiple checkpoints can be set and are handled on a stack-based basis (Rollback always rolls back to **the last** checkpoint).
```rust
handler.rollback(3);
```
```rust
handler.checkpoint();
// Mutate the database
handler.rollback();
```
or 
```rust
handler.checkpoint();
handler.checkpoint();
// Mutate the database
handler.rollback();
handler.rollback();
```
Merge-based rollbacks was a very inconvenient way to use CheckpointDb and Testkit. It only makes sense to implement actual checkpoints to CheckpointDb.
* There is no place in the existing codebase where …
> CheckpointDb and handmade checkpoints [ECR-975]

- .travis.yml
`cargo-deadlinks` doesn't support `-V` version, but `cargo deadlinks` does.
> Fix cargo-deadlinks installation [ECR-1083]

- examples/cryptocurrency/src/lib.rs
A tiny change that needed to be done after https://github.com/exonum/exonum/pull/575 merge.
> Change pub(crate) to pub in crypto-currency example [ECR-1076]

- CHANGELOG.md
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/fabric/mod.rs
- exonum/src/helpers/fabric/shared.rs
- exonum/tests/config.rs
- exonum/tests/testdata/config/config0_pub.toml
- exonum/tests/testdata/config/config1_pub.toml
- exonum/tests/testdata/config/config2_pub.toml
- exonum/tests/testdata/config/config3_pub.toml
- exonum/tests/testdata/config/template.toml
Introduce `--validators-count` parameter to config template.
**Use case**: 
```
cryptocurrency generate-template common.toml --validators-count 4
...
cryptocurrency finalize ... --public-configs pub_1.toml pub_2.toml pub_3.toml pub_4.toml
```
If count of provided `pub_*.toml` files differ from `validators-count` panic will be raised.
```
error: Number of validators configs does not match number of validator keys.
```
**For discussion:**
* Method `override_validators_count()` is  probably is not optimal.
> Introduce '--validators-count' parameter to config template. [ECR-905]

- CHANGELOG.md
- exonum/src/crypto.rs
According to [documentation](https://doc.rust-lang.org/std/string/trait.ToString.html) 
> ToString shouldn't be implemented directly: Display should be implemented instead, and you get the ToString implementation for free.
Also I refactored types usage according to @vitvakatu [comment](https://github.com/exonum/exonum/pull/318#issuecomment-377505152) (not sure if I made it as it was supposed to).
There are explicit [usages](https://github.com/exonum/exonum/blob/master/testkit/tests/counter/main.rs#L567) of `Hash::to_string` with `format!`. Now it can be removed but I am not sure if we should make it.
>  Implement `Display` for public sodium types

- CHANGELOG.md
- exonum/src/blockchain/transaction.rs
The following `transactions!` usage is now possible:
```rust
transactions!{}
```
> Make `transactions!` macro support empty body. [ECR-1133]

- CHANGELOG.md
- exonum/src/blockchain/transaction.rs
Changed signature of method with_description in ExecutionError structure to
`pub fn with_description<T : Into<String>>(code: u8, description: T) -> Self`
Now we can pass &str arguments to this function.
> Modify method with_description in ExecutionError structure

- exonum/src/events/tests.rs
**Problem:**
`test_network_reconnect` fails on Windows.
When we drop TestHandler, the outgoing `TcpStream` in `ConnectionsPool::connect_to_peer()` is not dropped and therefore we never receive `NetworkEvent::PeerDisconnected`. Problem with 
`mio::sys::windows::Selector`, issue is described here: https://github.com/carllerche/mio/issues/776
```
drop(t2);
assert_eq!(t1.wait_for_disconnect(), second);
```
Possible solutions:
* disconnect first handler from second and then drop.
* disable test on windows.
* patch mio crate.
I decided to disconnect from the second handler.
> Fix test_network_reconnect on windows. [ECR-446]

- services/time/src/lib.rs
Small pull-request to fix @andreyluchin's  comment about import ordering: https://github.com/exonum/exonum/pull/604#pullrequestreview-111911173
> Order modules to comply with conventions.

- exonum/src/helpers/metrics.rs
Fixes https://github.com/exonum/exonum/issues/606. `Utc::now`() is used instead.
> Replace SystemTime::now() with Utc::now()

- CHANGELOG.md
- exonum/src/encoding/error.rs
- exonum/src/encoding/fields.rs
- exonum/src/encoding/tests.rs
- exonum/src/helpers/fabric/details.rs
- exonum/tests/config.rs
To support IPv6 in exonum few things needed to be changed:
1. `SocketAddr` serialization;
2. IP address parsing in fabric;
3. IP address parsing in TOML (which happened to be needless since it's done with `serde` that already supports IPv6 in `SokcetAddr`).
While making this PR I found that we parse same data (IP addresses) differently in TOML (uses serde) and in command-line arguments (uses std), which seems odd.
Changes introduced after the review:
1. `const` moved to the top;
2. `SIZE_DIFF` is now a standalone constant;
3. `IpMode` enum instead of `bool` in tests.
I didn't write any tests for IPv6 parsing in TOML. It is parsed by `serde` crate, so it is its responsibility to cover that and the functionality is `std::net::SocketAddr`'s responsibility, but I still have doubts about that.
> IPv6 Support [ECR-158]

- CHANGELOG.md
- exonum/src/encoding/fields.rs
`fields.rs` had a lot of copy-pasted code, so I decided to move it into default implementation.
> Default `check` implementation for `Field` trait

- CHANGELOG.md
- exonum/src/node/consensus.rs
- exonum/tests/balance_service.rs
With only one node used, it was possible to execute the same transaction multiple times.
To prevent this, additional check was added into NodeHandler::handle_tx.
However, client gets response with tx_hash even for rejected transaction (and this behavior persists even when 2+ nodes are used).
I see no simple way to change it since NodeHandler::handle_tx doesn't return Result and thus not able to tell that transaction was rejected.
> Reject processed transactions [ECR-1251]

- CHANGELOG.md
- exonum/src/node/mod.rs
- exonum/tests/node.rs
The problem was caused by creating `Iron` handlers in separate threads.
Since those handlers won't stop without request, `join` call on them had no effect.
More than that, as creation of those handlers is non-blocking, there is no need in additional threads.
> Fix handling of shutdown request [ECR-1255]

- exonum/src/node/state.rs
Initial problem: with only 3 nodes started, if two of them gets disconnected and one restores after some time, it can't reach working node round.
The reason: incorrect max byzantine nodes amount calculation. It was calculated as (1/3) of all validators, while it should have been (1/3)-1.
After this fix, reconnected node can reach actual round without any problem.
---
I've tried to write a test for this behavior, but didn't succeed. As far as I can see, sandbox doesn't provide functionality to emulate node disconnect. Is there any way to emulate such a behavior?
> Fixed calculation of max byzantine nodes amount [ECR-1280]

- CHANGELOG.md
- exonum/src/helpers/fabric/details.rs
- exonum/src/node/mod.rs
- testkit/src/api.rs
Added `CorsMiddleware` to `create_private_api_handler` by `create_public_api_handler`'s example. 
Now method `create_private_api_handler` takes `config: &NodeApiConfig` parameter.
Do this changes are enough to support CORS in private API and do we need to test it and how?
> Core private API CORS support [ECR-1261]

- exonum/src/helpers/fabric/details.rs
Show the provided peer address when a parsing error occurred.
> Improved error message.

- exonum/src/node/consensus.rs
- exonum/src/node/state.rs
PR #680 didn't solved problem completely, since `add_round_timeout` wasn't called after `jump_to_round`.
This PR fixes it.
Also findings from the previous PR were fixed.
> Fix node round race [ECR-1280]

- exonum/src/storage/error.rs
There is no need for user to construct storage errors. Additionally, we treat such errors specifically during transactions execution and this mechanic can be misused.
> Make storage error constructor private (pub crate)

- exonum/src/helpers/fabric/maintenance.rs
https://travis-ci.org/exonum/exonum/jobs/380615039
```
WARNING: documentation for this crate may be rendered differently using the new Pulldown renderer.
See https://github.com/rust-lang/rust/issues/44229 for details.
WARNING: rendering difference in `Maintenance command.`
--> exonum/src/helpers/fabric/maintenance.rs:40:0
/html[0]/body[0] One element is missing: expected: `ul`
```
> Fix documentation rendering warning

- CHANGELOG.md
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/service.rs
- exonum/src/blockchain/tests.rs
- exonum/src/sandbox/sandbox.rs
- exonum/tests/node.rs
- services/time/src/lib.rs
- testkit/tests/service_hooks/hooks.rs
- testkit/tests/service_hooks/main.rs
`execute` method name is completely cryptic.
> rename `execute` to `execute_before_commit` and `handle_commit` to `after_commit`

- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency-advanced/backend/README.md
- examples/cryptocurrency/Cargo.toml
- testkit/Cargo.toml
Testkit depends on `cryptocurrency`, so it must be published too.
> Prepare examples for publishing

- exonum/src/blockchain/mod.rs
It'll make it easier to understand which error occurred and why
> Service name should be printed when writing errors to log [ECR-1471]

- services/configuration/src/transactions.rs
`Err(..)?` in those cases is not necessary.
> Replaced Err(..)? with return Err(..) in configuration service

- exonum/src/blockchain/service.rs
- exonum/src/node/mod.rs
API endpoint `consensus_enabled` returned` false` status at start because `SharedNodeState`'s constructor just calling `Default::default` and setting `is_enabled` by default to `false`.
So we need to set it to true manually or change the constructor.
> API endpoint consensus_enabled returns incorrect consensus status for validator node [ECR-1352]

- exonum/src/blockchain/service.rs
- exonum/src/node/basic.rs
- exonum/src/node/events.rs
- exonum/src/node/mod.rs
Add `is_validator` field in `NodeHandler` struct.
Set `is_enabled` to `false` is node is auditor, and block its changing.
Question: how can we test this functionality?
> Incorrect logic of "consensus_enabled" endpoint for auditor [ECR-1728]

- exonum/src/blockchain/service.rs
- exonum/src/node/state.rs
Now we updating `incoming/outgoing_connections` in `SharedNodeState::update` together with `peers_info`.
> GET {system_base_path}/peers doesn't return list of incoming connections [ECR-1375]

- examples/cryptocurrency-advanced/backend/src/transactions.rs
Now when someone trying to send funds to itself error `Error::SendingFundsToYourself` will be displayed.
> [Cryptocurrency-advanced] Transfer funds to yourself [ECR-1747]

- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/mod.rs
- exonum/src/node/connect_list.rs
- exonum/src/node/mod.rs
- exonum/src/sandbox/sandbox.rs
- exonum/tests/testdata/config/config01.toml
- exonum/tests/testdata/config/config02.toml
- exonum/tests/testdata/config/config03.toml
- exonum/tests/testdata/config/config04.toml
- exonum/tests/testdata/config/config12.toml
- exonum/tests/testdata/config/config13.toml
- exonum/tests/testdata/config/config14.toml
- exonum/tests/testdata/config/config23.toml
- exonum/tests/testdata/config/config24.toml
- exonum/tests/testdata/config/config34.toml
Change `ConnectList` representation in config from:
```toml
[connect_list.peers]
16ef83ca4b231404daec6d07b24beb84d89c25944285d2e32a2dcf8f0f3eda72 = "127.0.0.1:6333"
648e98a2405a40325d946bf8de6937795fe5c22ab095bca765a8b218e49ff5a3 = "127.0.0.1:6334"
```
to:
```toml
[[connect_list.peers]]
address = "127.0.0.1:6333"
public_key = "16ef83ca4b231404daec6d07b24beb84d89c25944285d2e32a2dcf8f0f3eda72"
[[connect_list.peers]]
address = "127.0.0.1:6334"
public_key = "648e98a2405a40325d946bf8de6937795fe5c22ab095bca765a8b218e49ff5a3"
```
This was to done to simplify parsing.
> Change ConnectList representation in config [ECR-1760]

- exonum/src/events/mod.rs
- exonum/src/events/noise/sodium_resolver.rs
- exonum/src/lib.rs
Low-level access to events code is required for benchmarking (part of [ECR-1585]).
As `events` module is still effectively private, I'm disabling `missing_debug_implementations` and `missing_docs` lints.
> Make 'events' mod public but doc(hidden)

- exonum/src/node/events.rs
- exonum/src/sandbox/consensus.rs
This flag must disable only consensus related events.
This PR re-enables `NetworkEvent`s and `ExternalMessage`s.
> Fix 'consensus_enabled' logic [ECR-1759]

- exonum/Cargo.toml
```text
warning: An explicit [[bench]] section is specified in Cargo.toml which currently                                            
disables Cargo from automatically inferring other benchmark targets.                                                         
This inference behavior will change in the Rust 2018 edition and the following                                               
files will be included as a benchmark target:                                                                                
* /home/ozkriff/bitfury/exonum/exonum/benches/storage.rs
This is likely to break cargo build or cargo test as these files may not be
ready to be compiled as a benchmark target today. You can future-proof yourself
and disable this warning by adding `autobenches = false` to your [package] …
```
> Disable auto bench detection to silence the warning [ECR-1617]

- CHANGELOG.md
- exonum/src/crypto/crypto_lib/sodiumoxide/x25519.rs
- exonum/src/crypto/macros.rs
- exonum/src/crypto/mod.rs
- exonum/src/storage/keys.rs
- testkit/tests/counter/main.rs
- testkit/tests/inflating_currency/main.rs
It has been found strange that Display trait prints entire representations while Debug truncates them to 4 bytes. Furthermore, some Debug impls add ellipsis and some don't.
Update the macros that generate Debug impls so that they print the entire byte range. Add some new tests to ensure that Display impls are covered as well. Drop now-unused constant for display length limit.
> Consistent compact Display/Debug format for crypto types

- exonum/src/sandbox/consensus.rs
Initially it was suggested in #716 to move these computations into a function, but actually these are constant values which do not depend on sandbox state, so we can move these complex values into variables.
I have reviewed uses of `sandbox.round_timeout()` and `PROPOSE_TIMEOUT` in the code, but they seem to be so diverse that it does not make much sense to give every one a constant. It makes sense for these ones though for the sake of readability.
> Extract block delays into varibles [ECR-1608]

- exonum/src/blockchain/config.rs
We have typical default length set to 1 MB for a reason. It is even [mentioned in documentation](https://exonum.com/doc/architecture/configuration/#genesisconsensus). Drop a warning if the user (accidentally) sets this value too low.
I pondered whether we need to output byte sizes in more user-friendly manner (i.e., as "1 MB" instead of "1048576"), but that's too much of a hassle for an event which should never happen.
Exonum binary serialization format has certain fixed-size components like message header before the body and a signature after the body. Using zero-sized bodies is not practical, but it will certainly not fly if the maximum message size does not allow even that.
I'd guess Exonum will fail to work if the message length does not allow consesus messages to get through, but …
> Validate ConsensusConfig::max_message_len [ECR-1055] (#621)

- cspell.sh
- exonum/build.rs
- exonum/src/crypto/crypto_lib/sodiumoxide/mod.rs
- exonum/src/events/noise/mod.rs
- exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs
- exonum/src/events/noise/wrappers/sodium_wrapper/wrapper.rs
- exonum/src/lib.rs
Cspell ignores files in subdirectories.
Maybe all these globs should be replaced with `find -name "*.rs` with correct ignore?
> Don't ignore files in sumbodules as dirs in cspell script [ECR-1851]

- CHANGELOG.md
- exonum/src/node/consensus.rs
- exonum/src/node/mod.rs
- exonum/src/sandbox/sandbox.rs
[Previously we have tweaked the timeout between **Propose** messages](https://github.com/exonum/exonum/pull/643) to adapt to current size of transaction queue. However, this timeout is fixed at the start of the round or at block creation time. If a node suddenly receives sufficiently large number of transactions during the timeout it will still wait for `max_propose_timeout()`.
Now we are going to check the transaction count every time we add a new transaction to the queue. If we have enough queued up then we schedule a quicker **Propose** timeout with `min_propose_timeout()`.
Previously scheduled timeouts will be handled later but they will be skipped due the checks in the beginning of `handle_propose_timeout()`.
Also note that we prevent expedited timeouts from being scheduled …
> Inject Proposes on transaction pressure [ECR-1441]

- exonum/src/node/consensus.rs
It turns out that `handle_propose_timeout()` calls way more common during network operation than I expected. We should actually allow expedited proposal to happen again only after we broadcast a real proposal to other nodes.
With this the nodes will no longer spam the log with bogus expedited timeout notifications. I should have found this earlier :( I remember now that someone in #844 has pointed out that this may not a good place to reset the flag.
> Fix expedited proposal reactivation [ECR-2040]

- exonum/src/node/consensus.rs
A node should not attempt to schedule a proposal on each transaction if it is not a leader. It will not work, the other nodes will notice this and will complain with errors in logs. We don't want that.
(Bug introduced by #844.)
> Schedule expedited proposals only if we're the leader [ECR-2038]

- exonum/src/sandbox/consensus/recovery.rs
- exonum/src/sandbox/consensus/transactions.rs
- exonum/src/sandbox/sandbox.rs
Here we introduce `SandboxBuilder` as a way to configure the `Sandbox` before usage. Currently it supports only setting a different genesis `ConsensusConfig`, but it can be extended in the future.
Tweakable consesus configuration enables writing some tests to verify dynamic Propose timeouts introduced in #844.
> SandboxBuilder and tests for dynamic propose timeout [ECR-2033]

- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/api/backends/actix.rs
- exonum/src/api/node/public/explorer.rs
- exonum/src/api/websocket.rs
- exonum/src/blockchain/service.rs
- testkit/Cargo.toml
* `Syn`/`Unsync` markers has been removed, they are not needed anymore.
* `actix::msgs::SystemExit` has been made private. now the system should be stopped by calling `System::stop()` which will send this message. Instead of passing SystemAddr just pass the System handle itself.
* `ws::start()` now accepts a reference to HttpRequest instead of instance.
* actix-web 0.7.3 has a regression (since 0.7.0) which breaks our tests. Apply a temporary workaround for it.
Obsoletes #814, #824.
> Update actix and actix-web to 0.7.3 [ECR-2121]

- exonum/tests/proof_map_index.rs
As it was discovered in #880, `prop_assert` was incorrectly used in the `proof_map_index` test to ensure some conditions hold at the beginning of the test.
> Use `prop_assume` in property testing for `ProofMapIndex`

- exonum/benches/criterion/block.rs
- exonum/benches/criterion/lib.rs
- exonum/src/blockchain/schema.rs
- exonum/src/blockchain/tests.rs
Unless I'm missing something, the cryptocurrency benchmark is as of now rendered unusable by at least two bugs:
- It generates duplicate transactions (each sender sends tokens to the same recipient each time). This distorts measurements and corresponds to a situation which can never occur in a real blockchain.
- ~All transactions panic because the initial balance of each account is 0, and we attempt to subtract from it. This distorts results, too.~ **Edit:** transactions don't really panic, as integer overflow is silently swallowed by the compiler in the release mode; it results in wrapping. Still, the code is not transparent; also, it's a bit of anecdotal evidence so far, but it seems that on my PC the benchmark with the overflow fixed runs ~10% slower (I don't really know why).
This PR …
> Fix cryptocurrency bench

- exonum/src/node/mod.rs
This fixes a weird feedback loop that spins up when a peer of a node is removed from its connect list and the node gets restarted.
Suppose there are three validator nodes: A, B, C. All of them are interconnected at the moment, present in each other's connect lists, and maintain mutual connections. Now node A is removed from node C's connect list and node C is restarted. Nodes A and B have no clue about that so they are still connected to C and will try connecting to it from time to time. However, C now does not wish to speak to A. Direct connections from C to A will be denied by the connect list, but if A has recently attempted talking to C then A will be present in C's peer list and C will try broadcasting messages to A.
We should not really broadcast messages to peers which are not …
> Do not broadcast to peers not in connect list [ECR-2156]

- exonum/Cargo.toml
- exonum/src/api/backends/actix.rs
- testkit/Cargo.toml
A straightforward update, but not without regressions. This was not mentioned in the changelog or migration guide, but it turned out that [`HttpServer::start()`](https://github.com/ilammy/exonum/blob/9ac19c7763a5999f5e5a8f7577a2cba2aa350dc2/exonum/src/api/backends/actix.rs#L335-L338) now returns `Server`, not `HttpServer`. `Addr<HttpServer>` is no longer a valid type, we should use the correct one instead. Remove the type alias altogether as it's used in only one place and it's not that hard to spell out.
Furthermore, our current version of actix-web 0.7.3 contained a regression bug which is fixed in 0.7.5. Remove now unnecessary workaround for this regression.
Supersedes #908, #923.
> Update actix-web to 0.7.5, remove workarounds [ECR-2149]

- CHANGELOG.md
- examples/cryptocurrency-advanced/backend/tests/api.rs
- exonum/src/sandbox/consensus/basic.rs
- exonum/src/storage/proof_map_index/proof.rs
- exonum/src/storage/proof_map_index/tests.rs
- exonum/tests/proof_map_index.rs
Tiny but useful change.
At EJB, we need to get raw proof data as fast as possible for sending it to the Java side.
I'm not sure. One of possible solutions would be marking this as `doc(hidden)` or even behind feature gate.
I need to hear your opinions.
UPD: Also includes change from `Vec` to `impl Iterator` for most public methods in `MapProof` API.
> Add all_entries_unchecked method [ECR-1959]

- exonum/src/events/network.rs
Moved `and_then` closures to separate messages.
> Some refactoring to make network.rs more clear

- exonum/src/events/network.rs
Don't close the stream of incoming connections when receiving an error.
> Don't close stream on error [ECR-2129]

- .travis.yml
This is needed to prevent Travis from building changes twice if a branch is pushed in addition to a pull request.
> Add master branch to 'safelist' [ECR-2387]

- exonum/tests/config.rs
This PR removes hardcoded length of a public key from `exonum/tests/config.rs`.
> Use PUBLIC_KEY_LENGTH constant instead of hardcoded integer

- CHANGELOG.md
- examples/cryptocurrency/examples/demo.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/fabric/maintenance.rs
- exonum/src/helpers/mod.rs
- exonum/src/node/mod.rs
- exonum/tests/config.rs
- exonum/tests/testdata/config/config_domain.toml
I propose to port this version of resolve by @aleksuss if it is enough.
How it will work:
you can use hostname:port in ConnectList in node's config file, but hostname will be resolved only on startup(which should cover almost all practical cases).
> Backport DNS resolve

- CHANGELOG.md
- exonum/src/node/mod.rs
- exonum/src/node/state.rs
- exonum/tests/testdata/config/config01.toml
- exonum/tests/testdata/config/config02.toml
- exonum/tests/testdata/config/config03.toml
- exonum/tests/testdata/config/config04.toml
- exonum/tests/testdata/config/config12.toml
- exonum/tests/testdata/config/config13.toml
- exonum/tests/testdata/config/config14.toml
- exonum/tests/testdata/config/config23.toml
- exonum/tests/testdata/config/config24.toml
- exonum/tests/testdata/config/config34.toml
This parameter hasn't been used, so it is OK to remove it completely.
> tx_pool_capacity parameter has been removed

- .travis.yml
- exonum/Cargo.toml
The stage became not actual because too many dependencies became not compatible with 1.27.2 and therefore this stage always is failed.
> Removed a build stage in CI by 1.27.2 version of Rust

- CHANGELOG.md
- exonum/src/storage/base_index.rs
- exonum/src/storage/db.rs
- exonum/src/storage/list_index.rs
This PR fixes incorrect behavior of the `clear()` method in indexes belonging to the same family. Before the fix, in certain situations the method cleared all indexes with the prefixes lexicographically greater than the one the method was invoked for. The explanatory test for `ListIndex` is supplied with the PR.
> Fix `clear` in indexes belonging to a family

- exonum/src/encoding/spec.rs
- exonum/src/messages/authorization.rs
- exonum/src/messages/mod.rs
- exonum/src/messages/protocol.rs
- exonum/src/messages/tests.rs
`Signed<T>` serialization contains a bug, that omit payload verification.
> Fix Signed<T> deserialization [ECR-2689]

- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency-advanced/backend/build.rs
- examples/cryptocurrency-advanced/backend/src/lib.rs
- examples/cryptocurrency-advanced/backend/src/proto/cryptocurrency.proto
- examples/cryptocurrency-advanced/backend/src/proto/mod.rs
- examples/cryptocurrency-advanced/backend/src/schema.rs
- examples/cryptocurrency-advanced/backend/src/transactions.rs
- examples/cryptocurrency-advanced/backend/src/wallet.rs
- examples/cryptocurrency-advanced/backend/tests/api.rs
- exonum-dictionary.txt
- exonum/Cargo.toml
- exonum/build.rs
- Convert **cryptocurrency-advanced** tutorial to Protobuf.
- Prototype 'linkage' of Exonum Core's protobuf definitions to external services via Cargo environment variables.
---
See: https://jira.bf.local/browse/ECR-2296
> Cryptocurrency advanced protobuf [ECR-2296]

- CHANGELOG.md
- examples/cryptocurrency-advanced/backend/build.rs
- exonum_build/src/lib.rs
- testkit/Cargo.toml
- testkit/build.rs
- testkit/examples/timestamping.rs
- testkit/examples/timestamping/main.rs
- testkit/examples/timestamping/proto/mod.rs
- testkit/examples/timestamping/proto/timestamping.proto
- testkit/src/lib.rs
- testkit/src/proto/mod.rs
- testkit/src/proto/testkit.proto
- testkit/src/proto/tests.proto
- testkit/src/server.rs
- testkit/tests/counter/counter.rs
- testkit/tests/counter/main.rs
- testkit/tests/counter/proto/counter.proto
- testkit/tests/counter/proto/mod.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
- testkit/tests/inflating_currency/main.rs
- testkit/tests/inflating_currency/proto/inflating_cryptocurrency.proto
- testkit/tests/inflating_currency/proto/mod.rs
- testkit/tests/service_hooks/hooks.rs
- testkit/tests/service_hooks/main.rs
- testkit/tests/service_hooks/proto/mod.rs
- testkit/tests/service_hooks/proto/service_hooks.proto
> Testkit to protobuf

- CHANGELOG.md
- exonum/benches/criterion/block.rs
- exonum/src/blockchain/transaction.rs
`Transaction::verify` is no more useful (and no more used) in Exonum 0.10
---
See: https://jira.bf.local/browse/ECR-2721
> Remove Transaction::verify method [ECR-2721]

- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/transaction.rs
This method will be used for broadcasting transactions by Java Bindings.
Any ideas about nicer interface are welcome
Additionally, `TransactionContext::new` method made public.
---
See: https://jira.bf.local/browse/ECR-2401
> Add Blockchain::broadcast_raw_transaction method [ECR-2401]

- exonum/src/api/node/private/mod.rs
Remove unused logs from the API handler.
> Remove unused logs from the API.

- exonum/Cargo.toml
- testkit/Cargo.toml
Criterion and ring dependency are not compatible(because of their lazy_static). 
We depend on ring through actix-web default feature.
This PR removes actix-web default features.
---
> Remove ring dependency(fix lazy_static)

- .travis.yml
- CHANGELOG.md
- components/crypto/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- examples/cryptocurrency/Cargo.toml
- examples/timestamping/backend/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
- services/time/Cargo.toml
- testkit/Cargo.toml
- testkit/server/Cargo.toml
Added feature `i128` to `byteorder` crate to include `LittleEndian::write_i128` and  `LittleEndian::write_u128` functions.
> Added feature i128 to byteorder crate

- CHANGELOG.md
- exonum/Cargo.toml
- exonum/src/helpers/fabric/builder.rs
- exonum/src/helpers/fabric/details.rs
- exonum/src/helpers/fabric/mod.rs
- exonum/src/helpers/fabric/password.rs
- exonum/src/helpers/fabric/shared.rs
- exonum/src/helpers/types.rs
- exonum/tests/config.rs
This PR allows following passphrase entry methods while generating configs and running node.
```--{service,consensus}-key-pass [stdin,env:VAR,pass:PASS]```
Default password entry method is stdin.
If variable in env is not set default one is used. (EXONUM_SERVICE_PASS, EXONUM_CONSENSUS_PASS)
---
See: https://jira.bf.local/browse/ECR-2519
> Improve key files password entry [ECR-2519]

- CHANGELOG.md
- exonum/src/api/node/public/explorer.rs
Changed a response code for the `/block` endpoint for the case when the requested block doesn't exist. And fixed a response for the genesis block.
---
See: 
https://jira.bf.local/browse/ECR-2974
https://jira.bf.local/browse/ECR-2975
> Changed a response code for the `/block` endpoint [ECR-2974 ECR-2975]

- services/time/README.md
Add reference to Java Time Oracle. Link will be valid after https://github.com/exonum/exonum-java-binding/pull/754 is merged.
---
See: https://jira.bf.local/browse/ECR-2896
> Add reference to Java Time Oracle [ECR-2896]

- CHANGELOG.md
- exonum/src/storage/base_index.rs
> Allow to use symbol `-` in index names

- .travis.yml
- components/crypto/Cargo.toml
- exonum/Cargo.toml
- services/configuration/Cargo.toml
Removed a build with nightly rust from Travis CI and updated some dependencies.
> Got rid off nightly rust in Travis CI

- CHANGELOG.md
- exonum/src/api/node/public/system.rs
A tiny improvement for light clients. Added possibility to get a list of available services with its id and service name. 
Example of response: 
```json
{
"services": [
{
"name": "configuration",
"id": 1
},
{
"name": "timestamping",
"id": 130
},
{
"name": "exonum_time",
"id": 4
}
]
}
```
> Added endpoint for displaying info about available services

- CHANGELOG.md
- exonum/src/api/node/public/system.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/tests/explorer/main.rs
- testkit/tests/system_api.rs
`system/v1/mempool` endpoint has been renamed into `system/v1/stats`.
An additional field in the response of the endpoint was added. The field
corresponds to the total number of transactions in the blockchain.
Example of the response: 
```json
{
"tx_pool_size": 1,
"tx_count": 315
}
```
> Added counter for transactions of the blockchain

- components/derive/Cargo.toml
- components/derive/src/lib.rs
- components/derive/src/tx_set.rs
- exonum-dictionary.txt
Several relatively minor improvements to `TransactionSet` derivation:
- It is now possible to specify message identifiers explicitly
- It is now possible to use boxed variants
- It is now possible to opt out from deriving anything for variant types, which breaks the macro if the variant types are external, or if the same variant type is reused with multiple `TransactionSet`s
> `TransactionSet` derivation improvements

- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/service.rs
- exonum/tests/node.rs
- services/configuration/src/lib.rs
- services/time/src/lib.rs
According to the MerkleDB a parameter of `initialize` method should be immutable reference to a   Fork.
> Use an immutable fork in initialize method

- components/merkledb/benches/refs.rs
- components/merkledb/src/db.rs
- components/merkledb/src/proof_map_index/proof.rs
- components/merkledb/src/views/metadata.rs
- components/merkledb/src/views/mod.rs
- components/merkledb/src/views/refs.rs
- examples/cryptocurrency-advanced/backend/src/schema.rs
- examples/cryptocurrency/src/lib.rs
- examples/timestamping/backend/src/schema.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/src/blockchain/service.rs
- exonum/src/helpers/fabric/maintenance.rs
- services/configuration/src/schema.rs
- services/time/examples/simple_service/main.rs
- services/time/src/schema.rs
- services/time/tests/test_exonum_time.rs
- testkit/tests/counter/counter.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
- Restore snapshot method in `ServiceContext`.
>  Small fixes in exonum-merkledb

- CHANGELOG.md
- components/merkledb/src/map_index.rs
- components/merkledb/src/proof_map_index/mod.rs
- components/merkledb/src/proof_map_index/tests.rs
- services/configuration/src/lib.rs
A number of elements for MapIndex and ProofMapIndex now stored in state.
---
> Add len() to MapIndex and ProofMapIndex

- exonum/src/api/node/public/explorer.rs
- testkit/tests/counter/main.rs
Return 404 error for latest param exceed current height.
---
> Weird error-prone behaviour of latest param in blocks explorer API endpoint[ECR-3188]

- exonum/src/api/mod.rs
- exonum/src/blockchain/mod.rs
- exonum/src/runtime/configuration_new/mod.rs
- exonum/src/runtime/configuration_new/schema.rs
- exonum/src/runtime/configuration_new/transactions.rs
- exonum/src/runtime/dispatcher.rs
- exonum/src/runtime/error.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/service.rs
- exonum/src/runtime/rust/tests.rs
- Implemented `DispatcherBuilder` to hide logic of built-in services creation.
- Renamed `RuntimeEnvironment` to `Runtime`.
- Added `service_id` method to `TransactionContext`.
> A small amount of code improvements. [ECR-3222]

- testkit/src/api.rs
- testkit/tests/counter/counter.rs
- testkit/tests/counter/main.rs
This PR improves HTTP API-related functionality of the testkit, allowing to modify HTTP requests before sending them (e.g., in order to add some headers). Another change is fixing `response_to_api_result` method in `RequestBuilder`, which previously did not convert `Unauthorized` API error correctly (the converter expected 403 HTTP status, while in reality `Unauthorized` error translates to 401 status.
> Improvements in `TestKitApi`

- exonum/src/api/node/public/explorer.rs
- exonum/tests/websocket/main.rs
If a service id is missing in transaction filter then no output for such subscription at all. 
---
See: https://jira.bf.local/browse/ECR-3297
> Check a service id in filter for transaction subscription [ECR-3297]

- CHANGELOG.md
- components/derive/src/tx_set.rs
- components/merkledb/src/macros.rs
- examples/cryptocurrency-advanced/backend/src/transactions.rs
- examples/cryptocurrency/src/lib.rs
- examples/timestamping/backend/src/transactions.rs
- exonum/benches/criterion/block.rs
- exonum/src/blockchain/tests.rs
- exonum/src/lib.rs
- exonum/src/node/mod.rs
- exonum/src/proto/macros.rs
- exonum/src/proto/mod.rs
- exonum/src/sandbox/config_updater.rs
- exonum/src/sandbox/mod.rs
- exonum/src/sandbox/timestamping.rs
- exonum/tests/explorer/blockchain/mod.rs
- exonum/tests/websocket/blockchain/mod.rs
- services/configuration/src/transactions.rs
- services/time/examples/simple_service/main.rs
- services/time/src/transactions.rs
- testkit/examples/timestamping/main.rs
- testkit/src/server.rs
- testkit/tests/counter/counter.rs
- testkit/tests/inflating_currency/inflating_cryptocurrency.rs
- testkit/tests/service_hooks/hooks.rs
Moving because this macro is used to implement `BinaryValue` trait for protobuf messages.
> Move `impl_binary_value_for_message` macros to proto module.

- CHANGELOG.md
- exonum/examples/explorer.rs
- exonum/src/api/node/public/explorer.rs
- exonum/src/api/websocket.rs
- exonum/src/blockchain/transaction.rs
- exonum/src/explorer/mod.rs
- exonum/tests/explorer/main.rs
- testkit/tests/counter/counter.rs
- testkit/tests/counter/main.rs
Endpoints: `/api/explorer/v1/block` and `/api/explorer/v1/transactions` 
---
See: https://jira.bf.local/browse/ECR-3349
> Extend responses for endpoints [ECR-3349]

- exonum/src/node/mod.rs
This PR adds some basic validation for `mempool.events_pool_capacity` parameters.
I was going to use the [Keats/validator](https://github.com/Keats/validator) crate initially, but it doesn't save much code and it's `#[validate(range(min = "18", max = "20"))]` attribute requires both min and max for some reason. So I decided to just add a plain validation function that can be modified easily in case of any refactorings of the configuration logic.
---
See: https://jira.bf.local/browse/ECR-3125
> Add some basic node config validation [ECR-3125]

- components/merkledb/Cargo.toml
- exonum/Cargo.toml
- exonum/src/lib.rs
EJB needs to control what features are enabled. It can also be useful for some of the users in the future (when they will be able to change rocksdb compression algorithm via options).
Also reexported merkledb crate
---
> Reexport RocksDB features and disable default ones [ECR-3382]

- components/merkledb/src/proof_map_index/mod.rs
- components/merkledb/src/sparse_list_index.rs
- components/merkledb/src/views/metadata.rs
- components/merkledb/src/views/tests.rs
Handle an error when we can't read an index state due different index types
---
See: https://jira.bf.local/browse/ECR-3418
> Handle an error when we can't read an index state [ECR-3418]

- exonum/examples/sample_runtime.rs
- exonum/src/blockchain/tests.rs
- exonum/src/runtime/dispatcher/mod.rs
- exonum/src/runtime/mod.rs
- exonum/src/runtime/rust/mod.rs
In some cases runtime forgets about deployed but not registered artifacts, for example after restart between artifact confirmation and registration.
To fix this issue we have to add `is_artifact_deployed` to runtime trait and mark artifact deploy error during the registration as fatal.
> Try to re deploy artifact before registration.

- exonum/src/helpers/mod.rs
The new function is needed for implementing `clear-cache` action of the maintenance command. As the function is used for internal purposes, no changelog updates are made.
---
See: https://jira.bf.local/browse/ECR-3482
> Add clear_consensus_messages_cache function [ECR-3482]

- .travis.yml
A try to fix an issue with timeout in TravisCI.
> Change cache structure in travis

- components/merkledb/src/views/metadata.rs
- components/merkledb/src/views/tests.rs
Somehow it turned out that provided index address name was lost on the `index_metadata` call step.
This PR fixes it and adds a test so it won't happen anymore.
> Set address name in index_metadata [ECR-3578]

- components/derive/src/service_factory.rs
- exonum/src/api/node/mod.rs
- exonum/src/api/node/public/system.rs
- exonum/src/runtime/mod.rs
Returning reference is not really handy.
> Use strings for protobuf files

- cli/src/lib.rs
- examples/cryptocurrency/examples/demo.rs
- exonum/benches/criterion/block.rs
- exonum/src/blockchain/builder.rs
- exonum/src/blockchain/mod.rs
- exonum/src/node/mod.rs
- exonum/src/sandbox/mod.rs
- exonum/tests/explorer/blockchain/mod.rs
- exonum/tests/node.rs
- exonum/tests/websocket/blockchain/mod.rs
Currently we aren't able to create a node with additional runtimes with `exonum-cli`.
> Add support of external runtimes to exonum-cli

- exonum/src/runtime/mod.rs
Extend docstring for `Runtime::shutdown`.
> Clarify runtime shutdown method [ECR-3696]

- exonum/src/proto/schema/exonum/runtime.proto
- exonum/src/runtime/error.rs
Use an enum in the proto files to avoid the manual bookkeeping of constants in java/python.
---
See: https://jira.bf.local/browse/ECR-3717
> Use enum to represent ErrorKind [ECR-3717]

- components/build/src/lib.rs
- components/merkledb/Cargo.toml
- components/merkledb/build.rs
- components/merkledb/src/lib.rs
- components/merkledb/src/proof_list_index/key.rs
- components/merkledb/src/proof_list_index/mod.rs
- components/merkledb/src/proof_list_index/proof.rs
- components/merkledb/src/proto/list_proof.proto
- components/merkledb/src/proto/mod.rs
- exonum-dictionary.txt
Manual implementation of `ProtobufConvert` for `ListProof`. Derive will be implemented later in separate task.
> Implement ProtobufConvert for ListProof

- services/supervisor/src/api.rs
- services/supervisor/src/proto_structures.rs
- services/supervisor/src/simple/api.rs
- services/supervisor/src/simple/mod.rs
- services/supervisor/tests/simple.rs
- services/time/tests/test_exonum_time.rs
This PR enhances the `SimpleSupervisor` with check for proposal author to be a validator (as in `Supervisor`). For node administrator workflow is not the same as for `Supervisor`: request with config proposal should be sent through private API endpoint.
However, this is the only check performed, there is no need to send request by all validators, and there is no need to send confirmations as well.
---
See: https://jira.bf.local/browse/ECR-3742
> SimpleSupervisor: Verify that config proposal is sent by validator [ECR-3742]

- examples/sample_runtime/src/main.rs
- exonum/benches/criterion/block.rs
- exonum/src/api/mod.rs
- exonum/src/api/node/public/explorer.rs
- exonum/src/api/node/public/system.rs
- exonum/src/api/websocket.rs
- exonum/src/blockchain/mod.rs
- exonum/src/node/mod.rs
- exonum/src/runtime/api.rs
- exonum/src/runtime/rust/mod.rs
- exonum/tests/explorer/blockchain/mod.rs
- test-suite/testkit/src/lib.rs
- test-suite/testkit/tests/counter/counter.rs
This method removes `ApiContext` structure and replaces its usage with `Blockchain`, since their layout became the same.
**Also**, this PR reduces the visibility of the `Blockchain::into_mut` method, since it's not really clear that this method should be called only once, and it's easy to misuse it (e.g. one can try to obtain the `Fork` with that method, which is completely incorrect).
However, that doesn't affect the public interface, since this method is just a sugar for (also public) `BlockchainBuilder`.
> Remove ApiContext structure [ECR-3745]

- exonum/src/messages/types.rs
- exonum/src/proto/schema/exonum/consensus.proto
Implement `hash(SignedMessage) = hash(payload || key.bytes || sign.bytes)` as specified in `consensus.proto`.
> Implement ObjectHash for SignedMessage

- exonum/src/blockchain/mod.rs
- exonum/tests/explorer/blockchain/mod.rs
- test-suite/testkit/tests/service_hooks/main.rs
`api_sender` is used by `sandbox` and it seems that there is no easy way to make this field private too. However, the visibility is `pub(crate)` anyway, so I guess it's no big deal.
> Encapsulate Blockchain fields [ECR-3222]

- exonum/src/runtime/rust/call_context.rs
- services/supervisor/src/lib.rs
- services/supervisor/src/transactions.rs
- services/supervisor/tests/supervisor/config.rs
- services/supervisor/tests/supervisor/inc.rs
We either apply the config with all the changes, or don't apply it at all.
So the `isolate` method is not required anymore.
Slippery moments:
- We still have to panic to rollback changes (will be fixed once we'll be able to return an error in `before_commit`).
- If panic/error occurs during config applying, the proposal is not removed (well, in fact it's removed but then rolled back). However I've added a check in the config proposal tx for it, so it's not a big problem I guess.
> Remove isolate method [ECR-3820]

- .travis.yml
For using latest version of kcov.
---
> Use code coverage util from master branch

- components/derive/src/lib.rs
- exonum/src/runtime/error.rs
- exonum/src/runtime/rust/mod.rs
- exonum/src/runtime/rust/service.rs
At the moment, examples are situated in the `exonum-derive` crate, therefore there is no way to test them. This PR moves examples to the documentations of the corresponding traits:
> Write proper examples for the Exonum traits derivation [ECR-3822]

- exonum/src/proto/schema/exonum/runtime.proto
Resolves the compile warning:
[WARNING] PROTOC: runtime.proto:21:1: warning: Import blockchain.proto but not used.
---
> Remove unused import

- test-suite/testkit/src/api.rs
- test-suite/testkit/src/lib.rs
> Restore warn(missing_docs) in testkit [ECR-3877]

- components/merkledb/src/access/extensions.rs
- components/merkledb/src/group.rs
- components/merkledb/src/lazy.rs
Invoke `panic!` to make errors more verbose.
> Explicit panic invocation in from_access

- .travis.yml
- exonum-dictionary.txt
- exonum/src/runtime/rust/api.rs
- test-suite/exonum-py-tests/README.md
This PR makes dependencies for `exonum-py-tests` be installed on `travis` from `github` (so we can easily update them without releases).
**Note:** Integrational tests will probably fail until https://github.com/exonum/exonum-python-client/pull/45 and https://github.com/exonum/exonum-launcher/pull/32 will be merged.
> Update travis config to use exonum-launcher from master branch

- CHANGELOG.md
- components/merkledb/src/db.rs
- components/merkledb/src/key_set_index.rs
- components/merkledb/src/list_index.rs
- components/merkledb/src/views/mod.rs
- components/merkledb/tests/common/mod.rs
- components/merkledb/tests/list.rs
- components/merkledb/tests/map.rs
- components/merkledb/tests/set.rs
This PR fixes incorrect implementation of `Snapshot` for `Patch`. The previous implementation didn't take into account that indexes can be deleted within the `Patch`; this led to potential stale / inconsistent reads from `Patch`es or `Fork`s.
Independently, the byte iterator implementation for `ViewChanges` was incorrect; it entered an infinite loop in `peek()` once a `Delete` change was encountered. This bug was not previously exposed since the `peek` method was not used; but with the correction of `Patch` behavior, the situation has changed.
> Fix couple of bugs in MerkleDB

- exonum/src/api/node/mod.rs
- exonum/tests/websocket/main.rs
WebSocket could not receive any information if different kinds of WebSockets connected.
For example:
1. The block WebSocket is connected.
2. The tx WebSocket is connected.
3. The client of the block WebSocket cannot receive any block data.
The root cause is the ApiNodeState only has one address for WebSocket server's address, so I make the broadcast_server_address as a vector.
BTW, I didn't clean the address vector because the behavior of "shutdown_broadcast_server" only occurs during the node stops.
> Fix websocket issue during different kind of WebSocket connect

- components/merkledb/src/db.rs
- components/merkledb/src/migration.rs
- components/merkledb/src/views/metadata.rs
- components/merkledb/src/views/mod.rs
- components/merkledb/src/views/tests.rs
Previously, creating a phantom index based on `ReadonlyFork` could lead to weird side-effects, such as incorrect / hard to debug borrow errors. This is solved by making 1st-class phantom views.
> Fix `ReadonlyFork`

- exonum/src/blockchain/block.rs
- exonum/src/blockchain/config.rs
- exonum/src/blockchain/schema.rs
- exonum/src/blockchain/tests.rs
- exonum/src/lib.rs
- exonum/src/messages/types.rs
- exonum/src/proto/tests.rs
- exonum/src/runtime/rust/tests.rs
- exonum/src/runtime/types.rs
Removed `extern crate exonum_derive` in exonum.
> Remove extern crate exonum_derive in exonum [ECR-4004]

- components/crypto/Cargo.toml
- components/crypto/src/lib.rs
- components/merkledb/Cargo.toml
We target Rust 1.36, so newer crate versions may have to wait.
> Fix Rust compatibility

- exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs
- exonum/src/lib.rs
Removed `extern crate exonum_sodiumoxide` in exonum.
> Remove extern crate exonum_sodiumoxide in exonum [ECR-4004]

- exonum/src/api/backends/actix.rs
- exonum/src/api/manager.rs
- exonum/src/api/websocket.rs
- exonum/src/blockchain/config.rs
- exonum/src/events/error.rs
- exonum/src/events/network.rs
- exonum/src/events/noise/wrappers/sodium_wrapper/resolver.rs
- exonum/src/lib.rs
- exonum/src/node/basic.rs
- exonum/src/node/consensus.rs
- exonum/src/node/events.rs
- exonum/src/node/mod.rs
- exonum/src/node/requests.rs
- exonum/src/node/state.rs
- exonum/src/runtime/dispatcher/mod.rs
- exonum/src/runtime/rust/mod.rs
Removed `extern crate log` in exonum.
> Remove extern crate log in exonum [ECR-4004]

- components/merkledb/Cargo.toml
- components/merkledb/examples/migration.rs
- components/merkledb/src/db.rs
- components/merkledb/src/indexes/group.rs
- components/merkledb/src/migration.rs
- components/merkledb/src/migration/persistent_iter.rs
- components/merkledb/src/views/address.rs
- components/merkledb/src/views/metadata.rs
- components/merkledb/tests/migration.rs
- components/merkledb/tests/persistent_iter.rs
- exonum/src/runtime/migrations.rs
- test-suite/testkit/src/migrations.rs
- test-suite/testkit/tests/migrations/main.rs
This PR introduces scratchpads (the access to temporary data during migration that is removed at the end of migration, regardless of whether the migration is successful) and persistent iterators.
---
See: https://jira.bf.local/browse/ECR-4078 https://jira.bf.local/browse/ECR-4079
> Improve migration functionality [ECR-4078] [ECR-4079]

- CHANGELOG.md
- components/explorer/src/api.rs
- components/explorer/src/lib.rs
- components/merkledb/src/migration.rs
- exonum/src/blockchain/mod.rs
- exonum/src/blockchain/schema.rs
- exonum/src/proto/schema/exonum/blockchain.proto
- exonum/src/runtime/dispatcher/mod.rs
- test-suite/consensus-tests/tests/basic.rs
2^32 - 1 is plenty to index tx position in block.
The number of tx is already limited to a way smaller number.
See ECR-4083
[skip ci]
---
> Use uint32 for tx position in block: [ECR-4083]

- cli/tests/cli.rs
The PR fixes the test `master_key_path_current_dir` which fails on windows host.
> Fix a test checking paths on windows host

- cli/src/lib.rs
DefaultConfigManager is needed for node instantiation with custom cli implementation.
---
> Make DefaultConfigManager public

- components/merkledb/src/migration.rs
"Not `entry`!" alone might leave the reader
bewildered (as the index is an Entry).
> Clarify why not 'entry':

- exonum/src/proto/schema/exonum/runtime.proto
Follow-up for #1680.
Improves the docstrings in the `runtime.proto`.
> Improve ExecutionError docs in runtime.proto

- exonum/src/messages/signed.rs
- exonum/src/proto/mod.rs
- exonum/src/proto/schema/exonum/messages.proto
- exonum/src/proto/schema/exonum/proofs.proto
Use `repeated SignedMessage` instead of  `repeated Verified` in `BlockProof` in the proto description.
---
See: https://jira.bf.local/browse/ECR-4108
> Change type for precommits in BlockProof [ECR-4108]

- test-suite/testkit/Cargo.toml
- test-suite/testkit/src/api.rs
This implementation is a complete fix not a workaround
> Fix segfault after TestKitApi dropping

- components/merkledb/src/access/extensions.rs
- components/merkledb/src/access/mod.rs
This PR improves documentation of the `access` module in MerkleDB crate and restricts the constructor of the `Prefixed` type.
> Improve `access` docs in MerkleDB

- components/merkledb/src/migration.rs
- exonum/src/runtime/migrations.rs
This PR clarifies split between `commit_migration` and `flush_migration` operations in the core.
---
See: https://jira.bf.local/browse/ECR-4148
> Clarify commit / flush split for migrations [ECR-4148]

- components/merkledb/src/views/metadata.rs
According to `create_index_metadata`,
ids are non-zero:
> Identifier should be non-zero to translate to
a correct id in `ResolvedAddress`
---
> Specify that ids are non-zero:

- services/supervisor/README.md
- services/supervisor/src/api.rs
- services/supervisor/src/lib.rs
- services/supervisor/tests/supervisor/deploy_failures.rs
- services/supervisor/tests/supervisor/migrations/mod.rs
- test-suite/testkit/src/api.rs
This PR adds a documentation for public and private REST API for supervisor.
Note that doctests are still sometimes failing due to some bug (which, as occurs, was not really fixed by the recent PR).
> Document supervisor api [ECR-4149]

- CHANGELOG.md
- components/merkledb/src/hash.rs
- components/merkledb/src/indexes/proof_map/key.rs
- components/merkledb/src/indexes/proof_map/mod.rs
- components/merkledb/src/indexes/proof_map/tests.rs
- components/merkledb/src/proto/list_proof.proto
- components/merkledb/src/proto/map_proof.proto
- components/merkledb/src/proto/mod.rs
This PR:
- unifies `ProofPath` serialization for hashing
- changes serialization of `MapProofEntry`
- replaces `BinaryKey` to `BinaryValue` as a constraint on `MapProof` keys for which Protobuf serialization is defined
---
See: https://jira.bf.local/browse/ECR-3485
> Breaking changes regarding Merkelized maps [ECR-3485]

- components/merkledb/src/access/mod.rs
- components/merkledb/src/generic.rs
- components/merkledb/src/lib.rs
- components/merkledb/src/migration.rs
- components/merkledb/src/views/mod.rs
This PR introduces access *enumerations* to MerkleDB, (hopefully) allowing to implement bindings more easily.
Discussion:
- Is this good enough for bindings?
---
See: https://jira.bf.local/browse/ECR-4174
> Generic access enumerations [ECR-4174]

- CHANGELOG.md
- exonum/src/runtime/blockchain_data.rs
Likely, it must be access.
---
> Fix the method name:

- test-suite/testkit/src/api.rs
Here we replace a cruel `SIGTERM`-based server stop with a gentler `StopService` message.
> Fix TestKit server crashes

- CHANGELOG.md
- components/merkledb/src/db.rs
- components/merkledb/src/generic.rs
- components/merkledb/src/lib.rs
This PR implements a version of `ReadonlyFork` with static lifetime. This version is then added to `GenericRawAccess` and used to implement `AsReadonly` for `GenericRawAccess`.
Discussion:
- Is `ReadonlyRcFork` a good name?
---
See: https://jira.bf.local/browse/ECR-4196
> Readonly fork with static lifetime [ECR-4196]

- exonum/src/runtime/blockchain_data.rs
I've actually understood that Java binding can't use `BlockchainData<GenericRawAccess>` everywhere and suddenly use `BlockchainData<&Fork>` from ExecutionContext.
---
> Use generic access in execution context

- CHANGELOG.md
- components/merkledb/src/indexes/proof_list/key.rs
- components/merkledb/src/indexes/proof_list/mod.rs
- components/merkledb/src/indexes/proof_list/proof.rs
- components/merkledb/src/indexes/proof_list/proof_builder.rs
- components/merkledb/src/indexes/proof_list/tests.rs
- examples/cryptocurrency/src/tx_tests.rs
This PR checks index / height "overflow" in `ListProof` and `ProofListIndex` methods. For example, `list.get(1 << 60)` previously panicked in the debug mode and returned garbage in the release mode; now it properly returns `None`.
Discussion:
- Is it appropriate to panic if the list length exceeds `1 << 56`? Is the error message output in this case good enough?
---
See: https://jira.bf.local/browse/ECR-4194
> Check index / height in `ProofListIndex` [ECR-4194]

- components/merkledb/tests/iter.rs
This PR introduces a property test for iterator methods. Since all index iterators now are implemented using `IndexIterator` trait, this makes it easier to (prop-)test them.
---
See: https://jira.bf.local/browse/ECR-4193
> Property testing for index iterators [ECR-4193]

- components/crypto/Cargo.toml
- components/explorer/Cargo.toml
- components/keys/Cargo.toml
- components/merkledb/Cargo.toml
- examples/cryptocurrency-advanced/backend/Cargo.toml
- exonum-node/Cargo.toml
- exonum/Cargo.toml
- services/explorer/Cargo.toml
- services/supervisor/Cargo.toml
- test-suite/testkit/Cargo.toml
Exactly what it says in the title. The reasoning is that we (yet?) need to support Rust 1.36 compilation target.
> Pin `hex` crate to version 0.4.0

- components/derive/src/exonum_interface.rs
- examples/cryptocurrency-advanced/backend/tests/multisig.rs
- runtimes/rust/src/stubs.rs
- services/middleware/src/transactions.rs
- services/supervisor/src/configure.rs
- test-suite/testkit/tests/interfaces/services.rs
This PR removes `MethodDescriptor.name` since it isn't used by the framework.
---
See: https://jira.bf.local/browse/ECR-4236
> Remove `MethodDescriptor.name` [ECR-4236]

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- exonum-node/src/sandbox/tests/round_details.rs
- exonum-node/src/state.rs
- test-suite/soak-tests/Cargo.toml
- test-suite/soak-tests/README.md
- test-suite/soak-tests/src/services.rs
- test-suite/soak-tests/src/toggle.rs
This PR fixes `Propose` invalidation logic. A `Propose` could be marked as invalid even if it did not contain invalid transactions, simply as a result of processing an unrelated invalid transaction.
Not done:
- Add tests for service switching on / off into the sandbox. Switching on / off seems to work fine, but more test coverage is always good.
- Fix panics on node shutdown (I'll create a separate Jira task for this).
---
See: https://jira.bf.local/browse/ECR-4223
> Fix `Propose` invalidation logic [ECR-4223]

- exonum-node/src/events/internal.rs
- exonum-node/src/lib.rs
- test-suite/soak-tests/src/toggle.rs
This PR fixes useless panic during node shutdown. While a panic doesn't make much difference in a typical app (the app is shut down together with a node, anyway), the panic led to complications in some high-level tests.
---
See: https://jira.bf.local/browse/ECR-4254
> Fix panic during node shutdown [ECR-4254]

- CHANGELOG.md
- test-suite/testkit/src/api.rs
- test-suite/testkit/src/lib.rs
This client allows to write code such this.
```rust
let client = testkit_api.client();
// This code doesn't work with the `testkit_api` because it doesn't implement `Send`.
tokio::spawn(async move {
// But works fine with the underlying client.
client.get(...)
});
```
> Add TestKitApiClient

- CHANGELOG.md
- cli/src/command/mod.rs
Make constants in `cli::command::generate_config` module public, as they are important for implementation of custom commands.
> Make public constants in cli::command::generate_config module [ECR-4341]

- CHANGELOG.md
- cli/src/command/run_dev.rs
- cli/src/lib.rs
- cli/tests/cli.rs
- cli/tests/node.rs
- `artifacts_dir` param renamed to `blockchain_path`
- removed cleaning of database files
- configuration files now stored in `config` subdirectory.
---
See: https://jira.bf.local/browse/ECR-4354
> Rework exonum_cli::RunDev [ECR-4354]

- CHANGELOG.md
- examples/cryptocurrency-advanced/backend/src/migrations/tests.rs
- services/supervisor/Cargo.toml
- services/supervisor/src/api.rs
- services/supervisor/src/lib.rs
- services/supervisor/src/proto/service.proto
- services/supervisor/src/proto_structures.rs
- services/supervisor/src/transactions.rs
- services/supervisor/tests/simple.rs
- services/supervisor/tests/supervisor/deploy_failures.rs
- services/supervisor/tests/supervisor/migrations/mod.rs
- services/supervisor/tests/supervisor/supervisor_config.rs
- services/supervisor/tests/supervisor/utils.rs
This PR fixes miscellaneous issues with the supervisor service:
- Error descriptions are made more complete and are logged when appropriate.
- `seed` fields are added into `DeployRequest` and `MigrateRequest`
- Navigation in the API docs is fixed
- ⚠️ Serialization is changed for supervisor POST endpoints, from hex-encoded Protobuf to ordinary JSON. This certainly breaks launcher and may break other stuff. It *seems* that the change doesn't affect supervisor soundness, but I may be mistaken.
---
See: https://jira.bf.local/browse/ECR-4346
> Supervisor brush-up [ECR-4346]

- CHANGELOG.md
- exonum-dictionary.txt
- runtimes/rust/src/lib.rs
- test-suite/rust-runtime-proto/src/tests.rs
- test-suite/testkit/Cargo.toml
- test-suite/testkit/src/api.rs
This PR allows to send POST requests with Protobuf-encoded payloads, and also fixes a bug with API endpoints not being updated if there are no services associated with the Rust runtime.
---
See: https://jira.bf.local/browse/ECR-3948
> Allow to POST Protobuf messages from `TestKitApi` [ECR-3948]

- exonum-node/src/events_impl.rs
- exonum/src/blockchain/mod.rs
- exonum/src/runtime/dispatcher/mod.rs
- exonum/src/runtime/dispatcher/tests.rs
- exonum/src/runtime/mod.rs
- runtimes/rust/tests/inspected/mod.rs
This PR removes `Runtime::shutdown()` method as redundant (runtimes can shut down in their `Drop` implementation).
---
See: https://jira.bf.local/browse/ECR-4359
> Remove `Runtime::shutdown()` [ECR-4359]

- exonum-node/src/basic.rs
- exonum-node/src/consensus.rs
- exonum-node/src/events_impl.rs
- exonum-node/src/lib.rs
- exonum-node/src/sandbox/mod.rs
- exonum-node/src/sandbox/sandbox_tests_helper.rs
- exonum-node/src/sandbox/tests/recovery.rs
- exonum-node/src/sandbox/tests/round_details.rs
- exonum-node/src/sandbox/tests/timeouts.rs
- exonum-node/src/state.rs
- exonum-node/tests/node.rs
- exonum/src/blockchain/config.rs
This PR enables creating block proposals after a node is started, i.e., not waiting for a round timeout (which is order of 3s with standard settings).
Discussion:
- Is the standard proposal timeout sufficient to establish connections with peers, etc.? (AFAIK, there is no way to rebroadcast a proposal to connecting peers.)
---
See: https://jira.bf.local/browse/ECR-4375
> Faster block proposals [ECR-4375]

- .travis.yml
- CHANGELOG.md
- components/api/src/manager.rs
- exonum-dictionary.txt
- exonum-node/Cargo.toml
- exonum-node/benches/transactions.rs
- exonum-node/src/events/internal.rs
- exonum-node/src/events/mod.rs
- exonum-node/src/events_impl.rs
- exonum-node/src/lib.rs
- exonum-node/src/sandbox/mod.rs
- exonum-node/tests/common/mod.rs
- exonum-node/tests/node.rs
- exonum-node/tests/signals.rs
- test-suite/soak-tests/src/bin/toggle.rs
- test-suite/testkit/src/lib.rs
This PR makes nodes process OS signals (namely, cross-platform "ctrl-c" corresponding to Unix's SIGINT; and SIGTERM on Unix).
Discussion:
---
See: https://jira.bf.local/browse/ECR-4374
> Signal handling by Exonum nodes [ECR-4374]

- CHANGELOG.md
- exonum-node/src/consensus.rs
- exonum-node/src/proposer.rs
- exonum-node/src/state.rs
- exonum/Cargo.toml
- exonum/benches/criterion/check_tx.rs
- exonum/benches/criterion/crypto.rs
- exonum/benches/criterion/lib.rs
- exonum/src/blockchain/mod.rs
- exonum/src/runtime/dispatcher/mod.rs
- exonum/src/runtime/dispatcher/tests.rs
- exonum/src/runtime/mod.rs
- services/explorer/src/api.rs
This PR caches results of `Blockchain::check_tx`. A simple benchmark included in the PR shows ~100x performance improvement, but it is unlikely that `check_tx` was a bottleneck before (it has provided throughput ~100K transactions per second even without caching).
---
See: https://jira.bf.local/browse/ECR-4376
> Cache `check_tx` results [ECR-4376]

- CHANGELOG.md
- exonum-dictionary.txt
- exonum/src/blockchain/block.rs
- exonum/src/blockchain/schema.rs
- exonum/src/proto/schema/exonum/proofs.proto
- exonum/src/proto/schema/exonum/runtime/errors.proto
- exonum/src/runtime/dispatcher/mod.rs
- exonum/src/runtime/error/error_match.rs
- exonum/src/runtime/error/execution_error.rs
- exonum/src/runtime/error/execution_status.rs
- exonum/src/runtime/error/mod.rs
- exonum/src/runtime/error/tests.rs
- exonum/src/runtime/execution_context.rs
- test-suite/testkit/tests/interfaces/main.rs
This PR adds backtrace to `ExecutionError`. 
---
See: https://jira.bf.local/browse/ECR-4353
> Error backtrace [ECR-4353]

- components/api/src/backends/actix.rs
- components/api/src/manager.rs
- exonum-dictionary.txt
Use `JsonBody` in the error responses.
Provide mechanism to override default error handlers.
> More verbose REST API error responses [ECR-2696]

- CHANGELOG.md
- components/api/Cargo.toml
- components/api/src/manager.rs
- components/system-api/Cargo.toml
- exonum-node/src/lib.rs
- runtimes/rust/Cargo.toml
- services/explorer/Cargo.toml
- test-suite/testkit/Cargo.toml
- test-suite/testkit/src/lib.rs
The PR add a possibility to set max allowed size of json payload receiving in request (e.g. size of a transaction) via `node.toml` config file in `api` section.
E.g. 
```toml
...
[private_config.api]
state_update_timeout = 10000
json_payload_size = 1048576
...
```
---
See: https://jira.bf.local/browse/ECR-4427
> Add a possibility to set max allowed json payload size [ECR-4427]

- CHANGELOG.md
- components/merkledb/src/backends/rocksdb.rs
- exonum/src/runtime/dispatcher/schema.rs
- services/supervisor/src/lib.rs
The PR fix performance regression occurs with time. The reason is that actively range deletion affects the time of getting an iterator of the column family. In hooks `before_transactions` and `commit_block`, we have exactly such behaviour. 
The PR adds two optimizations:
1. Providing `read_options` with setting true of param [ignore_range_deletions](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/options.h#L1606) to `iterator_cf_opt` and `get_opt` methods.
2. Cleaning indexes in the hooks only if they were not empty to decrease the number of operations with the database.
> Fix performance regression

- .github/workflows/ci.yml
- CHANGELOG.md
- components/merkledb/Cargo.toml
- components/merkledb/benches/benchmarks/mod.rs
- components/merkledb/benches/benchmarks/schema_patterns.rs
- components/merkledb/benches/benchmarks/storage.rs
- components/merkledb/benches/benchmarks/transactions.rs
- components/merkledb/src/backends/rocksdb.rs
- components/merkledb/src/backends/temporarydb/memory.rs
- components/merkledb/src/backends/temporarydb/mod.rs
- components/merkledb/src/backends/temporarydb/persisted.rs
- components/merkledb/src/indexes/proof_list/proof_builder.rs
- components/merkledb/src/indexes/proof_list/tests.rs
- components/merkledb/src/keys.rs
- components/merkledb/src/values.rs
- components/merkledb/src/views/metadata.rs
- components/merkledb/tests/backup.rs
- components/merkledb/tests/common/mod.rs
- components/merkledb/tests/iter.rs
- components/merkledb/tests/migration.rs
- components/merkledb/tests/persistent_iter.rs
- components/merkledb/tests/state_aggregation.rs
- exonum-dictionary.txt
- exonum-node/src/lib.rs
- exonum-node/src/pool.rs
- exonum-node/src/sandbox/mod.rs
- exonum/src/blockchain/config.rs
- runtimes/rust/benches/criterion/block.rs
- services/explorer/tests/api.rs
- test-suite/rust-runtime-proto/src/tests.rs
The PR adds a variant of TemporaryDB like a wrapper over RocksDB for testing the functionality of RockDB.
> Add a variant of TemporaryDB like a wrapper over RocksDB
